/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ChucNang_QL_NhanVien;

import DAO.BaoHiemDAO;
import java.awt.Color;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class SuaBaoHiem extends javax.swing.JFrame {

    /**
     * Creates new form SuaBaoHiem
     */
    BaoHiemDAO bhDAO;
    
    private Quanly.NhanVien nvForm;
    
    public SuaBaoHiem(Quanly.NhanVien nvForm) {
        initComponents();
        bhDAO = new BaoHiemDAO();
        this.nvForm = nvForm;
        
        //load data to combo box maBaoHiem
        loadDataToCB_maBH();
        
        cbMaBaoHiem.setSelectedIndex(0);
    }
    
    private void setWhiteColor()
    {
        bttSua_SuaBaoHiem.setForeground(Color.white);
        bttHuy_SuaBaoHiem.setForeground(Color.white);
    }
    
    private void loadDataToCB_maBH(){
        List<String> maBaoHiemList = new ArrayList<>();
        maBaoHiemList = bhDAO.getMaBHList();
        DefaultComboBoxModel<String> mode_pb = new DefaultComboBoxModel<>(maBaoHiemList.toArray(new String[0]));
        cbMaBaoHiem.setModel(mode_pb);
    }
    
    private void reLoadData(){
        BaoHiemDAO bhDAO = new BaoHiemDAO();
        List<Model.BaoHiem> BHList = new ArrayList<>();
        BHList = bhDAO.getBaoHiemList();
        nvForm.loadDataToTableBaoHiem(BHList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnThongTinNhanVien = new util.PanelGradient();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bttSua_SuaBaoHiem = new util.ButtonGradient();
        bttHuy_SuaBaoHiem = new util.ButtonGradient();
        tfMaNhanVien = new javax.swing.JTextField();
        tfNoiCap = new javax.swing.JTextField();
        tfGhiChu = new javax.swing.JTextField();
        cbMaBaoHiem = new javax.swing.JComboBox<>();
        tfNgayCapSo = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnThongTinNhanVien.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Thông tin Bảo Hiểm");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Mã bảo hiểm");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Mã nhân viên");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Ghi chú");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Ngày cấp số");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Nơi cấp");

        bttSua_SuaBaoHiem.setText("Sửa");
        bttSua_SuaBaoHiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttSua_SuaBaoHiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttSua_SuaBaoHiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttSua_SuaBaoHiemMouseExited(evt);
            }
        });
        bttSua_SuaBaoHiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSua_SuaBaoHiemActionPerformed(evt);
            }
        });

        bttHuy_SuaBaoHiem.setText("Hủy");
        bttHuy_SuaBaoHiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttHuy_SuaBaoHiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttHuy_SuaBaoHiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttHuy_SuaBaoHiemMouseExited(evt);
            }
        });
        bttHuy_SuaBaoHiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttHuy_SuaBaoHiemActionPerformed(evt);
            }
        });

        tfMaNhanVien.setEditable(false);
        tfMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfMaNhanVien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfNoiCap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfNoiCap.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfGhiChu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        cbMaBaoHiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaBaoHiemActionPerformed(evt);
            }
        });

        tfNgayCapSo.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout pnThongTinNhanVienLayout = new javax.swing.GroupLayout(pnThongTinNhanVien);
        pnThongTinNhanVien.setLayout(pnThongTinNhanVienLayout);
        pnThongTinNhanVienLayout.setHorizontalGroup(
            pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                                    .addGap(94, 94, 94)
                                    .addComponent(jLabel2)
                                    .addGap(195, 195, 195))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinNhanVienLayout.createSequentialGroup()
                                    .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbMaBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(39, 39, 39)
                                    .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfNoiCap)
                                        .addComponent(tfNgayCapSo, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))))
                            .addComponent(tfGhiChu)))
                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(bttSua_SuaBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(bttHuy_SuaBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnThongTinNhanVienLayout.setVerticalGroup(
            pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel13)
                        .addComponent(cbMaBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfNgayCapSo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14)
                    .addComponent(tfMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNoiCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttSua_SuaBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttHuy_SuaBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThongTinNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThongTinNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttSua_SuaBaoHiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttSua_SuaBaoHiemMouseEntered
        bttSua_SuaBaoHiem.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttSua_SuaBaoHiemMouseEntered

    private void bttSua_SuaBaoHiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttSua_SuaBaoHiemMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttSua_SuaBaoHiemMouseExited

    private void bttHuy_SuaBaoHiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_SuaBaoHiemMouseEntered
        bttHuy_SuaBaoHiem.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttHuy_SuaBaoHiemMouseEntered

    private void bttHuy_SuaBaoHiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_SuaBaoHiemMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttHuy_SuaBaoHiemMouseExited

    private void bttHuy_SuaBaoHiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttHuy_SuaBaoHiemActionPerformed
        this.dispose();
    }//GEN-LAST:event_bttHuy_SuaBaoHiemActionPerformed

    private void bttSua_SuaBaoHiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSua_SuaBaoHiemActionPerformed
        // TODO add your handling code here:
        if(PTPM_NHOM18.PTPM_NHOM18.kiemTraRong(pnThongTinNhanVien)){
            String maBaoHiem = cbMaBaoHiem.getSelectedItem().toString();
            try{
                String noiCap = tfNoiCap.getText();
                Date ngayCap = new Date(tfNgayCapSo.getDate().getTime());
                String ghiChu = tfGhiChu.getText();
                bhDAO.updateBaoHiem(noiCap, ngayCap, ghiChu, maBaoHiem);
                
                JOptionPane.showMessageDialog(null, "Update thành công!");
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error: Định dạng ngày không chính xác!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            }
            
            //reload data
            reLoadData();
        }else{
            JOptionPane.showMessageDialog(null, "Bạn chưa điền đầy đủ thông tin!");
        }
    }//GEN-LAST:event_bttSua_SuaBaoHiemActionPerformed

    private void cbMaBaoHiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaBaoHiemActionPerformed
        // TODO add your handling code here:
        String maBaoHiem = cbMaBaoHiem.getSelectedItem().toString();
        if(maBaoHiem.equals("")){
            
        }else{
            Model.BaoHiem bh = bhDAO.getBaoHiemByMaBH(maBaoHiem);
            tfMaNhanVien.setText(bh.getMaNV());
            tfNgayCapSo.setDate(bh.getNgayCap());
            tfNoiCap.setText(bh.getNoiCap());
            tfGhiChu.setText(bh.getGhiChu());
        }
    }//GEN-LAST:event_cbMaBaoHiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaBaoHiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaBaoHiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaBaoHiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaBaoHiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new SuaBaoHiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.ButtonGradient bttHuy_SuaBaoHiem;
    private util.ButtonGradient bttSua_SuaBaoHiem;
    private javax.swing.JComboBox<String> cbMaBaoHiem;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private util.PanelGradient pnThongTinNhanVien;
    private javax.swing.JTextField tfGhiChu;
    private javax.swing.JTextField tfMaNhanVien;
    private com.toedter.calendar.JDateChooser tfNgayCapSo;
    private javax.swing.JTextField tfNoiCap;
    // End of variables declaration//GEN-END:variables
}
