/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ChucNang_QL_NhanVien;

import DAO.LuongDAO;
import DAO.NVDAO;
import DAO.PhongBanDAO;
import Quanly.NhanVien;
import java.awt.Color;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import phantichthietkehethong_nhom4.Phantichthietkehethong_nhom4;

/**
 *
 * @author Admin
 */
public class SuaNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form SuaNhanVien
     */
    private final Quanly.NhanVien nvForm;
    NVDAO nvDAO;
    PhongBanDAO pbDAO;
    LuongDAO luongDAO;
    
    public SuaNhanVien(Quanly.NhanVien nvForm) {
        initComponents();
        nvDAO = new NVDAO();
        pbDAO = new PhongBanDAO();
        luongDAO = new LuongDAO();
        this.nvForm = nvForm;
    }
    
    private void setWhiteColor()
    {
        bttSua_SuaNhanVien.setForeground(Color.white);
        bttHuy_SuaNhanVien.setForeground(Color.white);
    }
    
    public void setDataToForm(String maNV, String hoTen, String gioiTinh, String danToc, String chucVu, String loaiHopDong, 
			String ngayDangKy, int thoiGian, String cMND_CCCD, String sDT, String hocVan, String email, String tenPB,
			String maLuong, String ghiChu){
        loadMaPBTo_PB();
        txtMaNV.setText(maNV);
        txtHoTen.setText(hoTen);
        cbGioiTinh.setSelectedItem(gioiTinh);
        cbDanToc.setSelectedItem(danToc);
        txtChucVu.setText(chucVu);
        cbLoaiHopDong.setSelectedItem(loaiHopDong);
        txtNgayDKy.setText(ngayDangKy);
        txtThoiGian.setText(String.valueOf(thoiGian));
        txtCCCD.setText(cMND_CCCD);
        txtSDT.setText(sDT);
        txtHocVan.setText(hocVan);
        txtEmail.setText(email);
        cbTenPB.setSelectedItem(tenPB);
        txtMaLuong.setText(maLuong);
        txtGhiChu.setText(ghiChu);
        
    }
    
    private void loadMaPBTo_PB(){
        //Load mã phòng ban vào combo box PB
        List<String> tenPBList = new ArrayList<>();
        tenPBList = pbDAO.getTenPBList();
        DefaultComboBoxModel<String> mode_pb = new DefaultComboBoxModel<>(tenPBList.toArray(new String[0]));
        cbTenPB.setModel(mode_pb);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnThongTinNhanVien = new util.PanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbTenPB = new javax.swing.JComboBox<>();
        txtHoTen = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        txtNgayDKy = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JTextField();
        cbGioiTinh = new javax.swing.JComboBox<>();
        cbDanToc = new javax.swing.JComboBox<>();
        txtSDT = new javax.swing.JTextField();
        txtHocVan = new javax.swing.JTextField();
        cbLoaiHopDong = new javax.swing.JComboBox<>();
        txtThoiGian = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        bttSua_SuaNhanVien = new util.ButtonGradient();
        bttHuy_SuaNhanVien = new util.ButtonGradient();
        txtGhiChu = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        txtMaLuong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnThongTinNhanVien.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin nhân viên");

        jLabel2.setText("Mã nhân Viên");

        jLabel3.setText("Phòng");

        jLabel4.setText("Họ tên");

        jLabel6.setText("Số CCCD");

        jLabel8.setText("Ngày ký");

        jLabel10.setText("Mã lương");

        jLabel11.setText("Ghi chú");

        cbTenPB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtHoTen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCCCD.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNgayDKy.setEditable(false);
        txtNgayDKy.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setText("Chức vụ");

        jLabel14.setText("Giới tính");

        jLabel15.setText("Dân tộc");

        jLabel16.setText("Số điện thoại");

        jLabel17.setText("Học vấn");

        jLabel18.setText("Loại hợp đồng");

        jLabel19.setText("Thời gian(năm)");

        jLabel20.setText("Email");

        txtChucVu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbGioiTinh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbDanToc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kinh", "Tày", "Thái", "Mường", "Nùng", "Dao", "H'Mông", "Khmer", "Hoa", "Chăm", "Ê Đê", "Ba Na", "Xơ Đăng", "Sán Chay", "Gia Rai", "Cơ Ho", "Mnông", "Pà Thẻn", "Stiêng", "Bru - Vân Kiều", "Tà Ôi", "Raglai", "Pu Péo", "Co", "Chứt", "Brau", "Xtiêng", "Cờ Lao", "La Chí", "La Ha", "Pà Hưng", "Sila", "Khmer Lo", "Bru - Vân Kiều", "Chứt", "Mạ", "Co", "Xtiêng", "Cờ Lao", "La Chí", "La Ha", "Pà Hưng", "Sila", "Khmer Lo", "Khơ Mú", "Lô Lô", "Mảng", "Pà Thẻn", "Pu Péo", "Rơ Măm", "Si La", "Tá Ôi", "Xơ Đăng", "Gia Rai" }));

        txtSDT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtHocVan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbLoaiHopDong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngắn hạn", "Dài hạn" }));
        cbLoaiHopDong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtThoiGian.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bttSua_SuaNhanVien.setText("Sửa");
        bttSua_SuaNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttSua_SuaNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttSua_SuaNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttSua_SuaNhanVienMouseExited(evt);
            }
        });
        bttSua_SuaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSua_SuaNhanVienActionPerformed(evt);
            }
        });

        bttHuy_SuaNhanVien.setText("Hủy");
        bttHuy_SuaNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttHuy_SuaNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttHuy_SuaNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttHuy_SuaNhanVienMouseExited(evt);
            }
        });
        bttHuy_SuaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttHuy_SuaNhanVienActionPerformed(evt);
            }
        });

        txtMaNV.setEditable(false);
        txtMaNV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtMaLuong.setEditable(false);
        txtMaLuong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnThongTinNhanVienLayout = new javax.swing.GroupLayout(pnThongTinNhanVien);
        pnThongTinNhanVien.setLayout(pnThongTinNhanVienLayout);
        pnThongTinNhanVienLayout.setHorizontalGroup(
            pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel20))
                .addGap(37, 37, 37)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                        .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtCCCD)
                            .addComponent(txtNgayDKy)
                            .addComponent(txtEmail)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaLuong)
                            .addComponent(cbTenPB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtChucVu)
                            .addComponent(txtSDT)
                            .addComponent(txtHocVan)
                            .addComponent(cbLoaiHopDong, 0, 180, Short.MAX_VALUE)
                            .addComponent(txtThoiGian)
                            .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDanToc, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                        .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel1)
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinNhanVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttSua_SuaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(bttHuy_SuaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        pnThongTinNhanVienLayout.setVerticalGroup(
            pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12)
                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDanToc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel3)
                    .addComponent(cbTenPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtHocVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtNgayDKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbLoaiHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtMaLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttSua_SuaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttHuy_SuaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnThongTinNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnThongTinNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttHuy_SuaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttHuy_SuaNhanVienActionPerformed
        this.dispose();
    }//GEN-LAST:event_bttHuy_SuaNhanVienActionPerformed

    private void bttHuy_SuaNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_SuaNhanVienMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttHuy_SuaNhanVienMouseExited

    private void bttHuy_SuaNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_SuaNhanVienMouseEntered
        bttHuy_SuaNhanVien.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttHuy_SuaNhanVienMouseEntered

    private void bttSua_SuaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSua_SuaNhanVienActionPerformed
        if(Phantichthietkehethong_nhom4.kiemTraRong(pnThongTinNhanVien)){
            String hoTen = txtHoTen.getText();
            String gioiTinh = cbGioiTinh.getSelectedItem().toString();
            String danToc = cbDanToc.getSelectedItem().toString();
            String chucVu = txtChucVu.getText();
            String loaiHopDong = cbLoaiHopDong.getSelectedItem().toString();
            int thoiGian;
            String CCCD = txtCCCD.getText();
            String SDT = txtSDT.getText();
            String hocVan = txtHocVan.getText();
            String email = txtEmail.getText();
            String maPB = pbDAO.getMaPBByTenPB(cbTenPB.getSelectedItem().toString());
            String ghiChu = txtGhiChu.getText();
            String maNV = txtMaNV.getText();
            try{
                thoiGian = Integer.parseInt(txtThoiGian.getText());
                nvDAO.suaNV(hoTen, gioiTinh, danToc, chucVu, loaiHopDong, thoiGian, CCCD, SDT, hocVan, email, maPB, ghiChu,maNV);
                
               JOptionPane.showMessageDialog(null, "Update thành công!");

                
                List<Model.NhanVien> NVList = nvDAO.getNVList();
                nvForm.loadDataToTableNhanVien(NVList);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Error: Nhập thời gian là 1 số!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "SQL error: CCCD đã tồn tại! \n" + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }catch(Exception j){
                JOptionPane.showMessageDialog(null, "Error: " + j.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

        }else{
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập đủ thông tin!");
        }
    }//GEN-LAST:event_bttSua_SuaNhanVienActionPerformed

    private void bttSua_SuaNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttSua_SuaNhanVienMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttSua_SuaNhanVienMouseExited

    private void bttSua_SuaNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttSua_SuaNhanVienMouseEntered
        bttSua_SuaNhanVien.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttSua_SuaNhanVienMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new SuaNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.ButtonGradient bttHuy_SuaNhanVien;
    private util.ButtonGradient bttSua_SuaNhanVien;
    private javax.swing.JComboBox<String> cbDanToc;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JComboBox<String> cbLoaiHopDong;
    private javax.swing.JComboBox<String> cbTenPB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private util.PanelGradient pnThongTinNhanVien;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtHocVan;
    private javax.swing.JTextField txtMaLuong;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgayDKy;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtThoiGian;
    // End of variables declaration//GEN-END:variables
}
