/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ChucNang_QL_NhanVien;

import DAO.LuongTVDAO;
import DAO.NVThuViecDAO;
import java.awt.Color;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import phantichthietkehethong_nhom4.Phantichthietkehethong_nhom4;

/**
 *
 * @author a
 */
public class SuaNVTV extends javax.swing.JFrame {

    /**
     * Creates new form SuaNVTV
     */
    private final Quanly.NhanVien nvForm;
    NVThuViecDAO nvtvDAO;
    LuongTVDAO luongTVDAO;
    
    public SuaNVTV(Quanly.NhanVien nvForm) {
        initComponents();
        this.nvForm = nvForm;
        luongTVDAO = new LuongTVDAO();
        nvtvDAO = new NVThuViecDAO();
    }
    
    public void setDataToForm(Model.HoSoThuViec nvtv){
        loadDataToCB_MaLTV();
        
        txtMaNVTV.setText(nvtv.getMaNVTV());
        txtHoTenTV.setText(nvtv.getHoTen());
        chooserNgaySinh.setDate(nvtv.getNgaySinh());
        txtCCCD_TV.setText(nvtv.getCMND_CCCD());
        cbMaLTV.setSelectedItem(nvtv.getMaLuongTV());
        txtViTriTV.setText(nvtv.getViTriThuViec());
        cbGioiTinhTV.setSelectedItem(nvtv.getGioiTint());
        txtSDT_TV.setText(nvtv.getSDT());
        txtHocVanTV.setText(nvtv.getHocVan());
        txtSoThangTV.setText(String.valueOf(nvtv.getSoThangThuViec()));
        txtGhiChuTV.setText(nvtv.getGhiChu());
    }
    
    private void reLoadData(){
        NVThuViecDAO nvtvDAO = new NVThuViecDAO();
        List<Model.HoSoThuViec> nvtvList = new ArrayList<>();
        nvtvList = nvtvDAO.getNVTVList();
        nvForm.loadDataToTableThuViec(nvtvList);
    }
    
    private void loadDataToCB_MaLTV(){
        List<String> maLuongTVList = luongTVDAO.getMaLTVList();
        DefaultComboBoxModel<String> mode_pb = new DefaultComboBoxModel<>(maLuongTVList.toArray(new String[0]));
        cbMaLTV.setModel(mode_pb);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnThongTinNhanVienThuViec = new util.PanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtHoTenTV = new javax.swing.JTextField();
        txtCCCD_TV = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtViTriTV = new javax.swing.JTextField();
        cbGioiTinhTV = new javax.swing.JComboBox<>();
        txtSDT_TV = new javax.swing.JTextField();
        txtHocVanTV = new javax.swing.JTextField();
        txtSoThangTV = new javax.swing.JTextField();
        bttSua_SuaNhanVien = new util.ButtonGradient();
        bttHuy_ThemSinhVien = new util.ButtonGradient();
        txtGhiChuTV = new javax.swing.JTextField();
        cbMaLTV = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtMaNVTV = new javax.swing.JTextField();
        chooserNgaySinh = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnThongTinNhanVienThuViec.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin nhân viên thử việc");

        jLabel4.setText("Họ tên");

        jLabel5.setText("Ngày sinh");

        jLabel6.setText("Số CCCD");

        jLabel10.setText("Mã lương TV");

        jLabel11.setText("Ghi chú");

        txtHoTenTV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCCCD_TV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setText("Vị trí thử việc");

        jLabel14.setText("Giới tính");

        jLabel16.setText("Số điện thoại");

        jLabel17.setText("Học vấn");

        jLabel19.setText("Số tháng thử việc");

        txtViTriTV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbGioiTinhTV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbGioiTinhTV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbGioiTinhTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGioiTinhTVActionPerformed(evt);
            }
        });

        txtSDT_TV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtHocVanTV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtSoThangTV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSoThangTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoThangTVActionPerformed(evt);
            }
        });

        bttSua_SuaNhanVien.setText("Sửa");
        bttSua_SuaNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttSua_SuaNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttSua_SuaNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttSua_SuaNhanVienMouseExited(evt);
            }
        });
        bttSua_SuaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSua_SuaNhanVienActionPerformed(evt);
            }
        });

        bttHuy_ThemSinhVien.setText("Hủy");
        bttHuy_ThemSinhVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttHuy_ThemSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttHuy_ThemSinhVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttHuy_ThemSinhVienMouseExited(evt);
            }
        });
        bttHuy_ThemSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttHuy_ThemSinhVienActionPerformed(evt);
            }
        });

        cbMaLTV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbMaLTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaLTVActionPerformed(evt);
            }
        });

        jLabel7.setText("Mã NVTV");

        txtMaNVTV.setEditable(false);
        txtMaNVTV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        chooserNgaySinh.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout pnThongTinNhanVienThuViecLayout = new javax.swing.GroupLayout(pnThongTinNhanVienThuViec);
        pnThongTinNhanVienThuViec.setLayout(pnThongTinNhanVienThuViecLayout);
        pnThongTinNhanVienThuViecLayout.setHorizontalGroup(
            pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinNhanVienThuViecLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinNhanVienThuViecLayout.createSequentialGroup()
                        .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinNhanVienThuViecLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(bttSua_SuaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                                .addComponent(bttHuy_ThemSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinNhanVienThuViecLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)))
                        .addGap(155, 155, 155))
                    .addGroup(pnThongTinNhanVienThuViecLayout.createSequentialGroup()
                        .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinNhanVienThuViecLayout.createSequentialGroup()
                                .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtHoTenTV)
                                        .addComponent(txtCCCD_TV)
                                        .addComponent(cbMaLTV, javax.swing.GroupLayout.Alignment.TRAILING, 0, 180, Short.MAX_VALUE)
                                        .addComponent(chooserNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtViTriTV, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnThongTinNhanVienThuViecLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSoThangTV, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnThongTinNhanVienThuViecLayout.createSequentialGroup()
                                        .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaNVTV, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSDT_TV, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHocVanTV, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbGioiTinhTV, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(txtGhiChuTV))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnThongTinNhanVienThuViecLayout.setVerticalGroup(
            pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinNhanVienThuViecLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHoTenTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtMaNVTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbGioiTinhTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGroup(pnThongTinNhanVienThuViecLayout.createSequentialGroup()
                        .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinNhanVienThuViecLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5))
                            .addComponent(chooserNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCCCD_TV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txtSDT_TV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cbMaLTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtHocVanTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtViTriTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtSoThangTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGhiChuTV, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinNhanVienThuViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttSua_SuaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttHuy_ThemSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThongTinNhanVienThuViec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThongTinNhanVienThuViec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbGioiTinhTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGioiTinhTVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGioiTinhTVActionPerformed

    private void txtSoThangTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoThangTVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoThangTVActionPerformed

    private void bttSua_SuaNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttSua_SuaNhanVienMouseEntered
        bttSua_SuaNhanVien.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttSua_SuaNhanVienMouseEntered

    private void bttSua_SuaNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttSua_SuaNhanVienMouseExited
//        setWhiteColor();
    }//GEN-LAST:event_bttSua_SuaNhanVienMouseExited

    private void bttSua_SuaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSua_SuaNhanVienActionPerformed
        // TODO add your handling code here:
        if(Phantichthietkehethong_nhom4.kiemTraRong(pnThongTinNhanVienThuViec)){
            String hoTen = txtHoTenTV.getText();
            Date ngaySinh;
            String CCCD = txtCCCD_TV.getText();
            String maLuongTV = cbMaLTV.getSelectedItem().toString();
            String viTriThuViec = txtViTriTV.getText();
            String gioiTinh = cbGioiTinhTV.getSelectedItem().toString();
            String SDT = txtSDT_TV.getText();
            String hocVan = txtHocVanTV.getText();
            int soThangTV;
            String ghiChu = txtGhiChuTV.getText();
            String maNVTV = txtMaNVTV.getText();
            try{
                soThangTV = Integer.parseInt(txtSoThangTV.getText());
                ngaySinh = new Date(chooserNgaySinh.getDate().getTime());
                nvtvDAO.updateNVTV(hoTen, ngaySinh, gioiTinh, CCCD, viTriThuViec, soThangTV, SDT, hocVan, maLuongTV, ghiChu, maNVTV);
                
                JOptionPane.showMessageDialog(null, "Update thành công!");

                reLoadData();
                this.dispose();
                Phantichthietkehethong_nhom4.resetForm(pnThongTinNhanVienThuViec);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Error: Nhập thời gian là 1 số!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "SQL error: CCCD đã tồn tại! \n" + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }catch(Exception j){
                JOptionPane.showMessageDialog(null, "Error: Sai định dạng ngày!" + j.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập đầy đủ thông tin!");
        }
    }//GEN-LAST:event_bttSua_SuaNhanVienActionPerformed

    private void bttHuy_ThemSinhVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_ThemSinhVienMouseEntered
        bttHuy_ThemSinhVien.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttHuy_ThemSinhVienMouseEntered

    private void bttHuy_ThemSinhVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_ThemSinhVienMouseExited
//        setWhiteColor();
    }//GEN-LAST:event_bttHuy_ThemSinhVienMouseExited

    private void bttHuy_ThemSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttHuy_ThemSinhVienActionPerformed
        this.dispose();
    }//GEN-LAST:event_bttHuy_ThemSinhVienActionPerformed

    private void cbMaLTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaLTVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaLTVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaNVTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaNVTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaNVTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaNVTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new SuaNVTV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.ButtonGradient bttHuy_ThemSinhVien;
    private util.ButtonGradient bttSua_SuaNhanVien;
    private javax.swing.JComboBox<String> cbGioiTinhTV;
    private javax.swing.JComboBox<String> cbMaLTV;
    private com.toedter.calendar.JDateChooser chooserNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private util.PanelGradient pnThongTinNhanVienThuViec;
    private javax.swing.JTextField txtCCCD_TV;
    private javax.swing.JTextField txtGhiChuTV;
    private javax.swing.JTextField txtHoTenTV;
    private javax.swing.JTextField txtHocVanTV;
    private javax.swing.JTextField txtMaNVTV;
    private javax.swing.JTextField txtSDT_TV;
    private javax.swing.JTextField txtSoThangTV;
    private javax.swing.JTextField txtViTriTV;
    // End of variables declaration//GEN-END:variables
}
