/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ChucNang_QL_NhanVien;

import DAO.BaoHiemDAO;
import DAO.NVDAO;
import java.awt.Color;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import phantichthietkehethong_nhom4.Phantichthietkehethong_nhom4;

/**
 *
 * @author Admin
 */
public class ThemBaoHiem extends javax.swing.JFrame {

    /**
     * Creates new form ThemBaoHiem
     */
    BaoHiemDAO bhDAO;
    NVDAO nvDAO;
    private final Quanly.NhanVien nvForm;
    
    public ThemBaoHiem(Quanly.NhanVien nvForm) throws SQLException {
        initComponents();
        bhDAO = new BaoHiemDAO();
        nvDAO = new NVDAO();
        this.nvForm = nvForm;
        
        //load data lên combo box
        loadDataToCB_maBH();
        
        //load data lên combo box maNV
        loadMaNVToCB_MaNV();
        
//        cbMaNV.setSelectedIndex(0);
    }
    
     private void setWhiteColor()
    {
       bttThem_ThemBaoHiem.setForeground(Color.white);
       bttHuy_ThemBaoHiem.setForeground(Color.white);  
    }
     
    private void loadDataToCB_maBH() throws SQLException{
        List<String> maBaoHiemList = new ArrayList<>();
        maBaoHiemList = bhDAO.getMaBHList();
        DefaultComboBoxModel<String> mode_pb = new DefaultComboBoxModel<>(maBaoHiemList.toArray(new String[0]));
        cbMaNV.setModel(mode_pb);
    }
    
    private void loadMaNVToCB_MaNV(){
        //Load mã phòng ban vào combo box maNV
        List<String> maNVList = new ArrayList<>();
        maNVList = nvDAO.getMaNVList0BH();
        DefaultComboBoxModel<String> mode_pb = new DefaultComboBoxModel<>(maNVList.toArray(new String[0]));
        cbMaNV.setModel(mode_pb);
    }
    
    private void reLoadData() throws SQLException{
        BaoHiemDAO bhDAO = new BaoHiemDAO();
        List<Model.BaoHiem> BHList = new ArrayList<>();
        BHList = bhDAO.getBaoHiemList();
        nvForm.loadDataToTableBaoHiem(BHList);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelGradient1 = new util.PanelGradient();
        pnThongTinBH = new util.PanelGradient();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bttThem_ThemBaoHiem = new util.ButtonGradient();
        bttHuy_ThemBaoHiem = new util.ButtonGradient();
        tfNoiCap = new javax.swing.JTextField();
        tfGhiChu = new javax.swing.JTextField();
        cbMaNV = new javax.swing.JComboBox<>();
        tfNgayCapSo = new com.toedter.calendar.JDateChooser();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnThongTinBH.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Thông tin bảo hiểm");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Mã nhân viên");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Ghi chú");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Ngày cấp số");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Nơi cấp");

        bttThem_ThemBaoHiem.setText("Thêm");
        bttThem_ThemBaoHiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttThem_ThemBaoHiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttThem_ThemBaoHiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttThem_ThemBaoHiemMouseExited(evt);
            }
        });
        bttThem_ThemBaoHiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttThem_ThemBaoHiemActionPerformed(evt);
            }
        });

        bttHuy_ThemBaoHiem.setText("Hủy");
        bttHuy_ThemBaoHiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttHuy_ThemBaoHiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttHuy_ThemBaoHiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttHuy_ThemBaoHiemMouseExited(evt);
            }
        });
        bttHuy_ThemBaoHiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttHuy_ThemBaoHiemActionPerformed(evt);
            }
        });

        tfNoiCap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfNoiCap.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfGhiChu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        cbMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaNVActionPerformed(evt);
            }
        });

        tfNgayCapSo.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout pnThongTinBHLayout = new javax.swing.GroupLayout(pnThongTinBH);
        pnThongTinBH.setLayout(pnThongTinBHLayout);
        pnThongTinBHLayout.setHorizontalGroup(
            pnThongTinBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinBHLayout.createSequentialGroup()
                .addGroup(pnThongTinBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinBHLayout.createSequentialGroup()
                        .addGroup(pnThongTinBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinBHLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel12)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinBHLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)))
                        .addGroup(pnThongTinBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnThongTinBHLayout.createSequentialGroup()
                                .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(tfNgayCapSo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfGhiChu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE))
                    .addGroup(pnThongTinBHLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(bttThem_ThemBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(bttHuy_ThemBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinBHLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(239, 239, 239))
            .addGroup(pnThongTinBHLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(tfNoiCap, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnThongTinBHLayout.setVerticalGroup(
            pnThongTinBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinBHLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addGroup(pnThongTinBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(tfNgayCapSo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnThongTinBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfNoiCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnThongTinBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(48, 48, 48)
                .addGroup(pnThongTinBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttThem_ThemBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttHuy_ThemBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThongTinBH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addComponent(pnThongTinBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttHuy_ThemBaoHiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttHuy_ThemBaoHiemActionPerformed
        this.dispose();
        
        try {
            reLoadData();
        } catch (SQLException ex) {
            Logger.getLogger(ThemBaoHiem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttHuy_ThemBaoHiemActionPerformed

    private void bttHuy_ThemBaoHiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_ThemBaoHiemMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttHuy_ThemBaoHiemMouseExited

    private void bttHuy_ThemBaoHiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_ThemBaoHiemMouseEntered
        bttHuy_ThemBaoHiem.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttHuy_ThemBaoHiemMouseEntered

    private void bttThem_ThemBaoHiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttThem_ThemBaoHiemMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttThem_ThemBaoHiemMouseExited

    private void bttThem_ThemBaoHiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttThem_ThemBaoHiemMouseEntered
        bttThem_ThemBaoHiem.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttThem_ThemBaoHiemMouseEntered

    private void bttThem_ThemBaoHiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttThem_ThemBaoHiemActionPerformed
        // TODO add your handling code here:
        if(Phantichthietkehethong_nhom4.kiemTraRong(pnThongTinBH,cbMaNV)){
            try{
                String maNV = cbMaNV.getSelectedItem().toString() == null ? " " : cbMaNV.getSelectedItem().toString();
                String noiCap = tfNoiCap.getText();
                Date ngayCap = new Date(tfNgayCapSo.getDate().getTime());
                String ghiChu = tfGhiChu.getText();

                if(maNV.equals(" ")){
                    JOptionPane.showMessageDialog(rootPane, "Tất cả nhân viên đã bảo hiểm!");
                }else{
                    try{
                        bhDAO.themBaoHiem(maNV, noiCap, ngayCap, ghiChu);
                        JOptionPane.showMessageDialog(null, "Thêm thành công!");
                        Phantichthietkehethong_nhom4.resetForm(pnThongTinBH);

                        reLoadData();
                    }catch(SQLException e){
                        JOptionPane.showMessageDialog(null, "SQL error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }catch(Exception m){
                JOptionPane.showMessageDialog(null, "Error: Định dạng ngày không đúng!", "Lỗi nhập liệu!", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin!");
        }
    }//GEN-LAST:event_bttThem_ThemBaoHiemActionPerformed

    private void cbMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemBaoHiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
//                new ThemBaoHiem().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.ButtonGradient bttHuy_ThemBaoHiem;
    private util.ButtonGradient bttThem_ThemBaoHiem;
    private javax.swing.JComboBox<String> cbMaNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private util.PanelGradient panelGradient1;
    private util.PanelGradient pnThongTinBH;
    private javax.swing.JTextField tfGhiChu;
    private com.toedter.calendar.JDateChooser tfNgayCapSo;
    private javax.swing.JTextField tfNoiCap;
    // End of variables declaration//GEN-END:variables
}
