/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ChucNang_QL_NhanVien;

import DAO.LuongDAO;
import DAO.NVDAO;
import DAO.PhongBanDAO;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import PTPM_NHOM18.PTPM_NHOM18;

/**
 *
 * @author Admin
 */
public class ThemNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinNhanVien
     */
     private Color color1 = new Color(0, 255, 204);
//    private Color color2 = Color.GREEN;
    private Color color3 = new Color(204, 0, 204);
    
    private Quanly.NhanVien nvForm;
    NVDAO nvDAO;
    PhongBanDAO pbDAO;
    LuongDAO luongDAO;
    
    public ThemNhanVien(Quanly.NhanVien nvForm) {
        
        initComponents();
        nvDAO = new NVDAO();
        pbDAO = new PhongBanDAO();
        luongDAO = new LuongDAO();
        this.nvForm = nvForm;
        
        //load data lên combo box tên pb
        loadTenPBToCB_TenPB();
        
        //load data lên combo box mã lương
        loadDataToCB_MALUONG();    
    }
    
    private void setWhiteColor()
    {
        bttThem_ThemNhanVien.setForeground(Color.white);
        bttHuy_ThemSinhVien.setForeground(Color.white);
    }
     
    private void loadTenPBToCB_TenPB(){
        //Load tên pb lên combo box tên PB
        List<String> tenPBList = new ArrayList<>();
        tenPBList = pbDAO.getTenPBList();
        DefaultComboBoxModel<String> mode_pb = new DefaultComboBoxModel<>(tenPBList.toArray(new String[0]));
        cbTenPB.setModel(mode_pb);
    }
    
    private void loadDataToCB_MALUONG(){
        List<String> maLuongList = new ArrayList<>();
        maLuongList = luongDAO.getMaLuongList();
//        maLuongList.remove(0);
        DefaultComboBoxModel<String> mode_pb = new DefaultComboBoxModel<>(maLuongList.toArray(new String[0]));
        cbMaLuong.setModel(mode_pb);
    }
    
    private void reLoadData(){
        List<Model.NhanVien> nvList = new ArrayList<>();
        nvList = nvDAO.getNVList();
        nvForm.loadDataToTableNhanVien(nvList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnThongTinNhanVien = new util.PanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbTenPB = new javax.swing.JComboBox<>();
        txtHoTen = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JTextField();
        cbGioiTinh = new javax.swing.JComboBox<>();
        cbDanToc = new javax.swing.JComboBox<>();
        txtSDT = new javax.swing.JTextField();
        txtHocVan = new javax.swing.JTextField();
        cbLoaiHopDong = new javax.swing.JComboBox<>();
        txtThoiGian = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        bttThem_ThemNhanVien = new util.ButtonGradient();
        bttHuy_ThemSinhVien = new util.ButtonGradient();
        txtGhiChu = new javax.swing.JTextField();
        cbMaLuong = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnThongTinNhanVien.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin nhân viên");

        jLabel3.setText("Phòng");

        jLabel4.setText("Họ tên");

        jLabel6.setText("Số CCCD");

        jLabel10.setText("Mã lương");

        jLabel11.setText("Ghi chú");

        cbTenPB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtHoTen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCCCD.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setText("Chức vụ");

        jLabel14.setText("Giới tính");

        jLabel15.setText("Dân tộc");

        jLabel16.setText("Số điện thoại");

        jLabel17.setText("Học vấn");

        jLabel18.setText("Loại hợp đồng");

        jLabel19.setText("Thời gian(năm)");

        jLabel20.setText("Email");

        txtChucVu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbGioiTinh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbDanToc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kinh", "Tày", "Thái", "Mường", "Nùng", "Dao", "H'Mông", "Khmer", "Hoa", "Chăm", "Ê Đê", "Ba Na", "Xơ Đăng", "Sán Chay", "Gia Rai", "Cơ Ho", "Mnông", "Pà Thẻn", "Stiêng", "Bru - Vân Kiều", "Tà Ôi", "Raglai", "Pu Péo", "Co", "Chứt", "Brau", "Xtiêng", "Cờ Lao", "La Chí", "La Ha", "Pà Hưng", "Sila", "Khmer Lo", "Bru - Vân Kiều", "Chứt", "Mạ", "Co", "Xtiêng", "Cờ Lao", "La Chí", "La Ha", "Pà Hưng", "Sila", "Khmer Lo", "Khơ Mú", "Lô Lô", "Mảng", "Pà Thẻn", "Pu Péo", "Rơ Măm", "Si La", "Tá Ôi", "Xơ Đăng", "Gia Rai" }));

        txtSDT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtHocVan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbLoaiHopDong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngắn hạn", "Dài hạn" }));
        cbLoaiHopDong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtThoiGian.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bttThem_ThemNhanVien.setText("Thêm");
        bttThem_ThemNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttThem_ThemNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttThem_ThemNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttThem_ThemNhanVienMouseExited(evt);
            }
        });
        bttThem_ThemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttThem_ThemNhanVienActionPerformed(evt);
            }
        });

        bttHuy_ThemSinhVien.setText("Hủy");
        bttHuy_ThemSinhVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttHuy_ThemSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttHuy_ThemSinhVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttHuy_ThemSinhVienMouseExited(evt);
            }
        });
        bttHuy_ThemSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttHuy_ThemSinhVienActionPerformed(evt);
            }
        });

        cbMaLuong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnThongTinNhanVienLayout = new javax.swing.GroupLayout(pnThongTinNhanVien);
        pnThongTinNhanVien.setLayout(pnThongTinNhanVienLayout);
        pnThongTinNhanVienLayout.setHorizontalGroup(
            pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel6))
                    .addComponent(jLabel11)
                    .addComponent(jLabel20)
                    .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(1, 1, 1)))
                .addGap(37, 37, 37)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                        .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19))
                            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbMaLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(cbTenPB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtHocVan)
                            .addComponent(txtThoiGian)
                            .addComponent(cbLoaiHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbDanToc, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                .addComponent(cbGioiTinh, javax.swing.GroupLayout.Alignment.LEADING, 0, 104, Short.MAX_VALUE)))
                        .addGap(39, 39, 39))
                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                        .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(118, Short.MAX_VALUE))))
            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(bttThem_ThemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttHuy_ThemSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinNhanVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(223, 223, 223))
        );
        pnThongTinNhanVienLayout.setVerticalGroup(
            pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cbDanToc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbTenPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtHocVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel18)
                    .addComponent(cbLoaiHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMaLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(pnThongTinNhanVienLayout.createSequentialGroup()
                        .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(pnThongTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttThem_ThemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttHuy_ThemSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThongTinNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThongTinNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttHuy_ThemSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttHuy_ThemSinhVienActionPerformed
        setVisible(false);
    }//GEN-LAST:event_bttHuy_ThemSinhVienActionPerformed

    private void bttThem_ThemNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttThem_ThemNhanVienMouseEntered
        bttThem_ThemNhanVien.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttThem_ThemNhanVienMouseEntered

    private void bttThem_ThemNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttThem_ThemNhanVienMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttThem_ThemNhanVienMouseExited

    private void bttHuy_ThemSinhVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_ThemSinhVienMouseEntered
        bttHuy_ThemSinhVien.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttHuy_ThemSinhVienMouseEntered

    private void bttHuy_ThemSinhVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_ThemSinhVienMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttHuy_ThemSinhVienMouseExited

    private void bttThem_ThemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttThem_ThemNhanVienActionPerformed
        // TODO add your handling code here:
        if(PTPM_NHOM18.kiemTraRong(pnThongTinNhanVien)){
            String hoTen = txtHoTen.getText();
            String gioiTinh = cbGioiTinh.getSelectedItem().toString();
            String danToc = cbDanToc.getSelectedItem().toString();
            String chucVu = txtChucVu.getText();
            String loaiHopDong = cbLoaiHopDong.getSelectedItem().toString();
            int thoiGian;
            String CCCD = txtCCCD.getText();
            String SDT = txtSDT.getText();
            String hocVan = txtHocVan.getText();
            String email = txtEmail.getText();
            String maPB = pbDAO.getMaPBByTenPB(cbTenPB.getSelectedItem().toString());
            String maLuong = cbMaLuong.getSelectedItem().toString();
            String ghiChu = txtGhiChu.getText();
            try{
                thoiGian = Integer.parseInt(txtThoiGian.getText());
                nvDAO.themNV(hoTen, gioiTinh, danToc, chucVu, loaiHopDong, thoiGian, CCCD, SDT, hocVan, email, maPB, maLuong, ghiChu);
                
                JOptionPane.showMessageDialog(null, "Thêm thành công!");
                PTPM_NHOM18.resetForm(pnThongTinNhanVien);
                //reload data
                reLoadData();
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Error: Nhập thời gian là 1 số!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "SQL error: CCCD đã tồn tại! \n" + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }catch(Exception j){
                JOptionPane.showMessageDialog(null, "Error: " + j.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        
        }else{
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa điền đầy đủ thông tin!");
        }
    }//GEN-LAST:event_bttThem_ThemNhanVienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         //</editor-fold>
         //</editor-fold>
         
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
//                new ThemNhanVien().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.ButtonGradient bttHuy_ThemSinhVien;
    private util.ButtonGradient bttThem_ThemNhanVien;
    private javax.swing.JComboBox<String> cbDanToc;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JComboBox<String> cbLoaiHopDong;
    private javax.swing.JComboBox<String> cbMaLuong;
    private javax.swing.JComboBox<String> cbTenPB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private util.PanelGradient pnThongTinNhanVien;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtHocVan;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtThoiGian;
    // End of variables declaration//GEN-END:variables
}
