/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NhanVien;

import DAO.ChamCongDAO;
import DAO.LuongDAO;
import DAO.NVDAO;
import DAO.TinhLuongDAO;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import PTPM_NHOM18.PTPM_NHOM18;

/**
 *
 * @author Admin
 */
public class ThongTinCaNhan extends javax.swing.JPanel {

    /**
     * Creates new form ThongTinCaNhan
     */
    private String maNV;
    NVDAO nvDAO;
    LuongDAO luongDAO;
    TinhLuongDAO tinhLuongDAO;
    ChamCongDAO lsccDAO;
    List<Model.TinhLuong> tinhLuongList;
    
    public ThongTinCaNhan(String maNV) {
        initComponents();
        this.maNV = maNV;
        
        nvDAO = new NVDAO();
        luongDAO = new LuongDAO();
        tinhLuongDAO = new TinhLuongDAO();
        lsccDAO = new ChamCongDAO();
        
        //set data
        setDataTTCN();
        setDataBLCN();
        
        tinhLuongList = tinhLuongDAO.getListTinhLuong();
        loadDataToTableTinhLuong(tinhLuongList);
         
    }
    
    private void adjustColumnWidths(JTable myTable){
        // Giả sử bảng của bạn có tên là "yourTableName"
        JTable table = myTable;

        // Lấy mô hình cột của bảng
        TableColumnModel columnModel = table.getColumnModel();

        // Lặp qua tất cả các cột để đặt chiều rộng nếu cần thiết
        for (int i = 0; i < columnModel.getColumnCount(); i++) {
            TableColumn column = columnModel.getColumn(i);
            column.setPreferredWidth(120); // Bạn có thể tùy chỉnh giá trị này
        }

    }
    
    private void setDataTTCN(){
        Model.NhanVien nv = nvDAO.getNVByMaNV(maNV);
        txtMaNhanVien_TTCN.setText(nv.getMaNV());
        txtPhong_TTCN.setText(nv.getMaPB());
        txtHoTen_TTCN.setText(nv.getHoTen());
        txtGioiTinh_TTCN.setText(nv.getGioiTinh());
        txtSoCCCD_TTCN.setText(nv.getCMND_CCCD());
        txtNgayKy_TTCN.setText(nv.getNgayDangKy().toString());
        txtDanToc_TTCN.setText(nv.getDanToc());
        txtMaLuong_TTCN.setText(nv.getMaLuong());
        txtChucVu_TTCN.setText(nv.getChucVu());
        txtSDT_TTCN.setText(nv.getSDT());
        txtHocVan_TTCN.setText(nv.getHocVan());
        txtLoaiHopDong_TTCN.setText(nv.getLoaiHopDong());
        txtEmail.setText(nv.getEmail());
        jTextField17.setText(String.valueOf(nv.getThoiGian()));
        jTextField18.setText(nv.getGhiChu());
    }
    
    private void setDataBLCN(){
        Model.NhanVien nv = nvDAO.getNVByMaNV(maNV);
        String maLuong = nv.getMaLuong();
        Model.Luong luong = luongDAO.getLuongByMaLuong(maLuong);
        txtMaLuong_BLCN.setText(luong.getMaLuong());
        txtLuongCoBan_BLCN.setText(String.valueOf(luong.getLuongCoBan()));
        txtPhuCapCV_BLCN.setText(String.valueOf(luong.getPhuCapCV()));
        txtPhuCapKhac_BLCN.setText(String.valueOf(luong.getPhuCapKhac()));
        txtGhiChu_BLCN.setText(luong.getGhiChu());
    }
    
    private void loadDataToTableTinhLuong(List<Model.TinhLuong> tinhLuongList){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã nhân viên");
        dtm.addColumn("Mã lương");
        dtm.addColumn("Tháng");
        dtm.addColumn("Năm");
        dtm.addColumn("Lương cơ bản");
        dtm.addColumn("Phụ cấp CV");
        dtm.addColumn("Phụ cấp khác");
        dtm.addColumn("Tiền thưởng");
        dtm.addColumn("Tiền kỷ luật");
        dtm.addColumn("Tiền hoa hồng");
        dtm.addColumn("Số ngày công");
        dtm.addColumn("Lương thực nhận");
        dtm.addColumn("Ghi chú");
        
        Object[] row = new Object[13];
        for(Model.TinhLuong tl: tinhLuongList){
            row[0] = tl.getMaNV();
            row[1] = tl.getLuong().getMaLuong();
            row[2] = tl.getThang();
            row[3] = tl.getNam();
            row[4] = tl.getLuong().getLuongCoBan();
            row[5] = tl.getLuong().getPhuCapCV();
            row[6] = tl.getLuong().getPhuCapKhac();
            row[7] = tl.getTienThuong();
            row[8] = tl.getTienKyLuat();
            row[9] = tl.getTienHoaHong();
            row[10] = tl.getSoNgayCong();
            row[11] = tl.getLuongThucNhan();
            row[12] = tl.getGhiChu();
            dtm.addRow(row);
        }
        tbl_TinhLuong.setModel(dtm);
        adjustColumnWidths(tbl_TinhLuong);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new util.PanelGradient();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtThongTinCaNhan = new javax.swing.JTextField();
        jPTTCaNhan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        gt = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMaNhanVien_TTCN = new javax.swing.JTextField();
        txtPhong_TTCN = new javax.swing.JTextField();
        txtHoTen_TTCN = new javax.swing.JTextField();
        txtSoCCCD_TTCN = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNgayKy_TTCN = new javax.swing.JTextField();
        txtMaLuong_TTCN = new javax.swing.JTextField();
        txtChucVu_TTCN = new javax.swing.JTextField();
        txtGioiTinh_TTCN = new javax.swing.JTextField();
        txtLoaiHopDong_TTCN = new javax.swing.JTextField();
        txtHocVan_TTCN = new javax.swing.JTextField();
        txtSDT_TTCN = new javax.swing.JTextField();
        txtDanToc_TTCN = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_TinhLuong = new javax.swing.JTable();
        btnXem_CCCN = new util.ButtonGradient();
        btnReset_CCCN = new util.ButtonGradient();
        btnChamCong = new util.ButtonGradient();
        cbThang_CCCN = new com.toedter.calendar.JMonthChooser();
        cbNam_CCCN = new com.toedter.calendar.JYearChooser();
        txtChamCongCaNhan = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtLuongCoBan_BLCN = new javax.swing.JTextField();
        txtMaLuong_BLCN = new javax.swing.JTextField();
        txtPhuCapCV_BLCN = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtPhuCapKhac_BLCN = new javax.swing.JTextField();
        txtGhiChu_BLCN = new javax.swing.JTextField();
        txtxBangLuongCaNhan = new javax.swing.JTextField();

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtThongTinCaNhan.setBackground(new java.awt.Color(0, 153, 153));
        txtThongTinCaNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtThongTinCaNhan.setText("Thông tin cá nhân");
        txtThongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThongTinCaNhanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Mã nhân viên");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Ngày ký");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Dân tộc");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Phòng");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Họ tên");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Số CMND/CCCD");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Email");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("Mã lương");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Chức vụ");

        gt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        gt.setText("Giới tính");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setText("Số điện thoại");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setText("Học vấn");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setText("Loại hợp đồng");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setText("Thời gian");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Ghi chú");

        txtMaNhanVien_TTCN.setEditable(false);
        txtMaNhanVien_TTCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtMaNhanVien_TTCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtPhong_TTCN.setEditable(false);
        txtPhong_TTCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtPhong_TTCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtHoTen_TTCN.setEditable(false);
        txtHoTen_TTCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtHoTen_TTCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtSoCCCD_TTCN.setEditable(false);
        txtSoCCCD_TTCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtSoCCCD_TTCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNgayKy_TTCN.setEditable(false);
        txtNgayKy_TTCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtNgayKy_TTCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtMaLuong_TTCN.setEditable(false);
        txtMaLuong_TTCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtMaLuong_TTCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtChucVu_TTCN.setEditable(false);
        txtChucVu_TTCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtChucVu_TTCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtGioiTinh_TTCN.setEditable(false);
        txtGioiTinh_TTCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtGioiTinh_TTCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtLoaiHopDong_TTCN.setEditable(false);
        txtLoaiHopDong_TTCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtLoaiHopDong_TTCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtHocVan_TTCN.setEditable(false);
        txtHocVan_TTCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtHocVan_TTCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtSDT_TTCN.setEditable(false);
        txtSDT_TTCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtSDT_TTCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtDanToc_TTCN.setEditable(false);
        txtDanToc_TTCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtDanToc_TTCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField17.setEditable(false);
        jTextField17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextField17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField18.setEditable(false);
        jTextField18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextField18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Năm");

        javax.swing.GroupLayout jPTTCaNhanLayout = new javax.swing.GroupLayout(jPTTCaNhan);
        jPTTCaNhan.setLayout(jPTTCaNhanLayout);
        jPTTCaNhanLayout.setHorizontalGroup(
            jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTTCaNhanLayout.createSequentialGroup()
                .addGroup(jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTTCaNhanLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(gt))
                        .addGap(37, 37, 37)
                        .addGroup(jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoCCCD_TTCN, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtMaNhanVien_TTCN)
                            .addComponent(txtHoTen_TTCN)
                            .addComponent(txtGioiTinh_TTCN)))
                    .addGroup(jPTTCaNhanLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(txtPhong_TTCN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addGroup(jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4)
                    .addComponent(jLabel15))
                .addGap(51, 51, 51)
                .addGroup(jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtChucVu_TTCN, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(txtMaLuong_TTCN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNgayKy_TTCN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDanToc_TTCN, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT_TTCN, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTTCaNhanLayout.createSequentialGroup()
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addGroup(jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtLoaiHopDong_TTCN, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addComponent(txtHocVan_TTCN)
                        .addComponent(txtEmail))
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPTTCaNhanLayout.setVerticalGroup(
            jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTTCaNhanLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtMaNhanVien_TTCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayKy_TTCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtHocVan_TTCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPhong_TTCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDanToc_TTCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtLoaiHopDong_TTCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHoTen_TTCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtMaLuong_TTCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtChucVu_TTCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gt)
                    .addComponent(txtGioiTinh_TTCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(45, 45, 45)
                .addGroup(jPTTCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSoCCCD_TTCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtSDT_TTCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPTTCaNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtThongTinCaNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPTTCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 145, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông tin cá nhân", jPanel1);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel25.setText("Tháng");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel26.setText("Năm");

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        tbl_TinhLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_TinhLuong.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane4.setViewportView(tbl_TinhLuong);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        btnXem_CCCN.setText("Xem");
        btnXem_CCCN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXem_CCCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXem_CCCNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXem_CCCNMouseExited(evt);
            }
        });
        btnXem_CCCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXem_CCCNActionPerformed(evt);
            }
        });

        btnReset_CCCN.setText("Làm mới");
        btnReset_CCCN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReset_CCCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReset_CCCNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReset_CCCNMouseExited(evt);
            }
        });
        btnReset_CCCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset_CCCNActionPerformed(evt);
            }
        });

        btnChamCong.setText("Chấm công");
        btnChamCong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnChamCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChamCongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChamCongMouseExited(evt);
            }
        });
        btnChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamCongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(cbThang_CCCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbNam_CCCN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXem_CCCN, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnReset_CCCN, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(jLabel26)
                        .addComponent(btnXem_CCCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReset_CCCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbNam_CCCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(cbThang_CCCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(48, 48, 48)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        txtChamCongCaNhan.setBackground(new java.awt.Color(0, 153, 153));
        txtChamCongCaNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtChamCongCaNhan.setText("Chấm công cá nhân");
        txtChamCongCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChamCongCaNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtChamCongCaNhan)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtChamCongCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chấm công cá nhân", jPanel3);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel22.setText(" Mã lương");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel24.setText("Lương cơ bản");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setText("Phụ cấp CV");

        txtLuongCoBan_BLCN.setEditable(false);
        txtLuongCoBan_BLCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtLuongCoBan_BLCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtMaLuong_BLCN.setEditable(false);
        txtMaLuong_BLCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtMaLuong_BLCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtPhuCapCV_BLCN.setEditable(false);
        txtPhuCapCV_BLCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtPhuCapCV_BLCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel23.setText("Phụ cấp khác");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setText("Ghi chú");

        txtPhuCapKhac_BLCN.setEditable(false);
        txtPhuCapKhac_BLCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtPhuCapKhac_BLCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtGhiChu_BLCN.setEditable(false);
        txtGhiChu_BLCN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtGhiChu_BLCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel24)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaLuong_BLCN, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLuongCoBan_BLCN, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(txtPhuCapCV_BLCN))
                .addGap(154, 154, 154)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23))
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhuCapKhac_BLCN, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGhiChu_BLCN, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtMaLuong_BLCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtPhuCapKhac_BLCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLuongCoBan_BLCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtPhuCapCV_BLCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtGhiChu_BLCN))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtxBangLuongCaNhan.setBackground(new java.awt.Color(0, 153, 153));
        txtxBangLuongCaNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtxBangLuongCaNhan.setText("Bảng lương cá nhân");
        txtxBangLuongCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtxBangLuongCaNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(txtxBangLuongCaNhan, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(txtxBangLuongCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(415, 415, 415))
        );

        jTabbedPane1.addTab("Bảng lương cá nhân", jPanel2);

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtThongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThongTinCaNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThongTinCaNhanActionPerformed

    private void txtxBangLuongCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtxBangLuongCaNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtxBangLuongCaNhanActionPerformed

    private void txtChamCongCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChamCongCaNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChamCongCaNhanActionPerformed

    private void btnXem_CCCNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXem_CCCNMouseEntered
        btnXem_CCCN.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_btnXem_CCCNMouseEntered

    private void btnXem_CCCNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXem_CCCNMouseExited
        btnXem_CCCN.setForeground(Color.white);
    }//GEN-LAST:event_btnXem_CCCNMouseExited

    private void btnXem_CCCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXem_CCCNActionPerformed
        // TODO add your handling code here:
        int thang = cbThang_CCCN.getMonth()+1;
        int nam = cbNam_CCCN.getYear();
        tinhLuongList = tinhLuongDAO.getTinhLuongList(thang, nam);
        List<Model.TinhLuong> tinhLuong = new ArrayList<>();
        for(Model.TinhLuong tl: tinhLuongList){
            if(tl.getMaNV().equals(maNV)){
                tinhLuong.add(tl);
            }
        }
        
        //load data lên bảng 
        loadDataToTableTinhLuong(tinhLuong);
    }//GEN-LAST:event_btnXem_CCCNActionPerformed

    private void btnReset_CCCNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReset_CCCNMouseEntered
        btnReset_CCCN.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_btnReset_CCCNMouseEntered

    private void btnReset_CCCNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReset_CCCNMouseExited
        btnReset_CCCN.setForeground(Color.white);
    }//GEN-LAST:event_btnReset_CCCNMouseExited

    private void btnChamCongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChamCongMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChamCongMouseEntered

    private void btnChamCongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChamCongMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChamCongMouseExited

    private void btnReset_CCCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset_CCCNActionPerformed
        // TODO add your handling code here:
        PTPM_NHOM18.resetForm(jPanel10);
    }//GEN-LAST:event_btnReset_CCCNActionPerformed

    private void btnChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamCongActionPerformed
        // TODO add your handling code here:
        // Lấy thời gian hiện tại
        LocalTime currentTime = LocalTime.now();

        // Đặt thời gian giới hạn là 9h sáng (09:00)
        LocalTime limitTime = LocalTime.of(9, 0);

        // Kiểm tra nếu thời gian hiện tại trước 9h sáng
        if (currentTime.isBefore(limitTime)) {
            List<Model.LSChamCong> lscc = lsccDAO.checkCC(LocalDate.now().toString(), maNV);
            if (lscc.size() == 0) {
                lsccDAO.addChamCong(maNV);
                JOptionPane.showMessageDialog(panelGradient1, "Chấm công thành công!");
            } else {
                JOptionPane.showMessageDialog(panelGradient1, "Hôm nay đã chấm công! Hẹn gặp vào ngày mai.");
            }
        } else {
            // Nếu sau 9h sáng
            JOptionPane.showMessageDialog(panelGradient1, "Không thể chấm công sau 9h sáng!");
        }
    }//GEN-LAST:event_btnChamCongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.ButtonGradient btnChamCong;
    private util.ButtonGradient btnReset_CCCN;
    private util.ButtonGradient btnXem_CCCN;
    private com.toedter.calendar.JYearChooser cbNam_CCCN;
    private com.toedter.calendar.JMonthChooser cbThang_CCCN;
    private javax.swing.JLabel gt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPTTCaNhan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private util.PanelGradient panelGradient1;
    private javax.swing.JTable tbl_TinhLuong;
    public static javax.swing.JTextField txtChamCongCaNhan;
    private javax.swing.JTextField txtChucVu_TTCN;
    private javax.swing.JTextField txtDanToc_TTCN;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGhiChu_BLCN;
    private javax.swing.JTextField txtGioiTinh_TTCN;
    private javax.swing.JTextField txtHoTen_TTCN;
    private javax.swing.JTextField txtHocVan_TTCN;
    private javax.swing.JTextField txtLoaiHopDong_TTCN;
    private javax.swing.JTextField txtLuongCoBan_BLCN;
    private javax.swing.JTextField txtMaLuong_BLCN;
    private javax.swing.JTextField txtMaLuong_TTCN;
    private javax.swing.JTextField txtMaNhanVien_TTCN;
    private javax.swing.JTextField txtNgayKy_TTCN;
    private javax.swing.JTextField txtPhong_TTCN;
    private javax.swing.JTextField txtPhuCapCV_BLCN;
    private javax.swing.JTextField txtPhuCapKhac_BLCN;
    private javax.swing.JTextField txtSDT_TTCN;
    private javax.swing.JTextField txtSoCCCD_TTCN;
    public static javax.swing.JTextField txtThongTinCaNhan;
    public static javax.swing.JTextField txtxBangLuongCaNhan;
    // End of variables declaration//GEN-END:variables
}
