/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Quanly;


import DAO.BoPhanDAO;
import DAO.PhongBanDAO;
import Model.PhongBan;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import phantichthietkehethong_nhom4.Phantichthietkehethong_nhom4;
import util.PanelGradient;

/**
 *
 * @author Admin
 */

public class BoPhan extends javax.swing.JPanel {

    /**
     * Creates new form BoPhan
     */
    private final BoPhanDAO bpDAO;
    private final PhongBanDAO pbDAO;
    private List<Model.BoPhan> BPList;
    private List<Model.PhongBan> PBList;
    private PanelGradient gradientPanel;
    
    public BoPhan() {
        initComponents();
        bpDAO = new BoPhanDAO();
        pbDAO = new PhongBanDAO();
        
        loadMaBPToCB_BP();
        loadMaPBTo_PB();
        
        //Load data lên bảng BP
        BPList = new ArrayList<>();
        BPList = bpDAO.getBPList();
        loadDataToTableBP(BPList);
        
        //Load data lên bảng PB
        PBList = new ArrayList<>();
        PBList = pbDAO.getPBList();
        loadDataToTablePB(PBList);
              
        safetySelectedCB(cbMaBP_BP);
        safetySelectedCB(cbMaBP_PB);
        safetySelectedCB(cbMaPB_PB);
    }
    
    private void safetySelectedCB(JComboBox myCB){
        if (myCB.getItemCount() > 0 && myCB.getItemAt(0) != null) {
            myCB.setSelectedIndex(0);
        } else {
            myCB.setSelectedItem("");
        }
    }
    
    private void loadMaBPToCB_BP(){
        //Load mã bộ phận vào combo box BP
        List<String> tenBPList = new ArrayList<>();
        tenBPList = bpDAO.getMaBPList();
        DefaultComboBoxModel<String> model_bp = new DefaultComboBoxModel<>(tenBPList.toArray(new String[0]));
        cbMaBP_BP.setModel(model_bp);
        
        //Load mã bộ phận vào combo box BP_PB
        DefaultComboBoxModel<String> model_pb_bp = new DefaultComboBoxModel<>(tenBPList.toArray(new String[0]));
        cbMaBP_PB.setModel(model_pb_bp);
    }
    
    private void loadMaPBTo_PB(){
        //Load mã phòng ban vào combo box PB
        List<String> tenPBList = new ArrayList<>();
        tenPBList = pbDAO.getMaPBList();
        DefaultComboBoxModel<String> mode_pb = new DefaultComboBoxModel<>(tenPBList.toArray(new String[0]));
        cbMaPB_PB.setModel(mode_pb);
    }
    
    private void loadMaPBToCB_PB(List<String> maPBList){
        DefaultComboBoxModel<String> mode_pb = new DefaultComboBoxModel<>(maPBList.toArray(new String[0]));
        cbMaPB_PB.setModel(mode_pb);
    }
    
    private void setWhiteColor()
    {
        btnAddPB.setForeground(Color.white);
        btnUpdatePB.setForeground(Color.white);      
        btnResetPB.setForeground(Color.white);
        btnAddBP.setForeground(Color.white);
        btnUpdateBP.setForeground(Color.white);
        btnResetBP.setForeground(Color.white);
    }
    
    private void loadDataToTableBP(List<Model.BoPhan> BPList){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã bộ phận");
        dtm.addColumn("Tên bộ phận");
        dtm.addColumn("Ngày thành lập");
        dtm.addColumn("Ghi chú");
        
        Object[] row = new Object[4];
        for(Model.BoPhan bp: BPList){
            row[0] = bp.getMaBP();
            row[1] = bp.getTenBP();
            row[2] = bp.getNgayTLap();
            row[3] = bp.getGhiChu();
            dtm.addRow(row);
        }
        tbQuanLyBoPhan.setModel(dtm);
    }
    
    private void loadDataToTablePB(List<PhongBan> PBList){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã phòng ban");
        dtm.addColumn("Mã bộ phận");
        dtm.addColumn("Tên phòng ban");
        dtm.addColumn("Ngày thành lập");
        dtm.addColumn("Ghi chú");
        
        Object[] row = new Object[5];
        for(PhongBan pb: PBList){
            row[0] = pb.getMaPB();
            row[1] = pb.getMaBP();
            row[2] = pb.getTenPB();
            row[3] = pb.getNgayTLap();
            row[4] = pb.getGhiChu();
            dtm.addRow(row);
        }
        tbQuanLyPhongBan.setModel(dtm);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new util.PanelGradient();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPPB = new javax.swing.JPanel();
        txtQuanLyPhongBan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbMaBP_PB = new javax.swing.JComboBox<>();
        txtTenPB_PB = new javax.swing.JTextField();
        btnAddPB = new util.ButtonGradient();
        btnUpdatePB = new util.ButtonGradient();
        btnResetPB = new util.ButtonGradient();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbQuanLyPhongBan = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtGhiChu_PB = new javax.swing.JTextField();
        cbMaPB_PB = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPBoPhan = new javax.swing.JPanel();
        txtQuanLyBoPhan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbMaBP_BP = new javax.swing.JComboBox<>();
        txtTenBP = new javax.swing.JTextField();
        btnAddBP = new util.ButtonGradient();
        btnUpdateBP = new util.ButtonGradient();
        btnResetBP = new util.ButtonGradient();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbQuanLyBoPhan = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtGhiChu_BP = new javax.swing.JTextArea();

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1119, 884));

        txtQuanLyPhongBan.setBackground(new java.awt.Color(0, 153, 153));
        txtQuanLyPhongBan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQuanLyPhongBan.setText("Quản lý phòng ban");
        txtQuanLyPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuanLyPhongBanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel1.setText("Mã bộ phận");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setText("Mã phòng ban");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setText("Tên phòng ban");

        cbMaBP_PB.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        cbMaBP_PB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbMaBP_PB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaBP_PBActionPerformed(evt);
            }
        });

        txtTenPB_PB.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txtTenPB_PB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAddPB.setText("Thêm phòng ban");
        btnAddPB.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnAddPB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddPBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddPBMouseExited(evt);
            }
        });
        btnAddPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPBActionPerformed(evt);
            }
        });

        btnUpdatePB.setText("Sửa phòng ban");
        btnUpdatePB.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnUpdatePB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdatePBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdatePBMouseExited(evt);
            }
        });
        btnUpdatePB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePBActionPerformed(evt);
            }
        });

        btnResetPB.setText("Làm mới");
        btnResetPB.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnResetPB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetPBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetPBMouseExited(evt);
            }
        });
        btnResetPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPBActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tbQuanLyPhongBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbQuanLyPhongBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickToGetDataPB(evt);
            }
        });
        jScrollPane1.setViewportView(tbQuanLyPhongBan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel9.setText("Ghi chú");

        txtGhiChu_PB.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txtGhiChu_PB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbMaPB_PB.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        cbMaPB_PB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbMaPB_PB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaPB_PBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPPBLayout = new javax.swing.GroupLayout(jPPB);
        jPPB.setLayout(jPPBLayout);
        jPPBLayout.setHorizontalGroup(
            jPPBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPBLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jPPBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPBLayout.createSequentialGroup()
                        .addGroup(jPPBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPPBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMaBP_PB, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMaPB_PB, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPPBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPPBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenPB_PB, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtGhiChu_PB))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPPBLayout.createSequentialGroup()
                        .addComponent(btnAddPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(btnUpdatePB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(btnResetPB, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))))
            .addGroup(jPPBLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPPBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtQuanLyPhongBan))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPPBLayout.setVerticalGroup(
            jPPBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtQuanLyPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(jPPBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbMaBP_PB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenPB_PB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(txtGhiChu_PB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMaPB_PB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPPBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdatePB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Phòng ban", jPPB);

        txtQuanLyBoPhan.setBackground(new java.awt.Color(0, 153, 153));
        txtQuanLyBoPhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQuanLyBoPhan.setText("Quản lý bộ phận");
        txtQuanLyBoPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuanLyBoPhanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel5.setText("Mã bộ phận");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel6.setText("Tên bộ phận");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel7.setText("Ghi chú");

        cbMaBP_BP.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        cbMaBP_BP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbMaBP_BP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaBP_BPActionPerformed(evt);
            }
        });

        txtTenBP.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txtTenBP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAddBP.setText("Thêm bộ phận");
        btnAddBP.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnAddBP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddBPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddBPMouseExited(evt);
            }
        });
        btnAddBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBPActionPerformed(evt);
            }
        });

        btnUpdateBP.setText("Sửa bộ phận");
        btnUpdateBP.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnUpdateBP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateBPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateBPMouseExited(evt);
            }
        });
        btnUpdateBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBPActionPerformed(evt);
            }
        });

        btnResetBP.setText("Làm mới");
        btnResetBP.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnResetBP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetBPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetBPMouseExited(evt);
            }
        });
        btnResetBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetBPActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        tbQuanLyBoPhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbQuanLyBoPhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickToGetDataBP(evt);
            }
        });
        jScrollPane2.setViewportView(tbQuanLyBoPhan);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        txtGhiChu_BP.setColumns(20);
        txtGhiChu_BP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGhiChu_BP.setRows(5);
        jScrollPane3.setViewportView(txtGhiChu_BP);

        javax.swing.GroupLayout jPBoPhanLayout = new javax.swing.GroupLayout(jPBoPhan);
        jPBoPhan.setLayout(jPBoPhanLayout);
        jPBoPhanLayout.setHorizontalGroup(
            jPBoPhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBoPhanLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jPBoPhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBoPhanLayout.createSequentialGroup()
                        .addComponent(btnAddBP, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateBP, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(btnResetBP, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPBoPhanLayout.createSequentialGroup()
                        .addGroup(jPBoPhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPBoPhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenBP, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPBoPhanLayout.createSequentialGroup()
                                .addComponent(cbMaBP_BP, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBoPhanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPBoPhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtQuanLyBoPhan))
                .addGap(19, 19, 19))
        );
        jPBoPhanLayout.setVerticalGroup(
            jPBoPhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBoPhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtQuanLyBoPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPBoPhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBoPhanLayout.createSequentialGroup()
                        .addGroup(jPBoPhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbMaBP_BP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(16, 16, 16)
                        .addGroup(jPBoPhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTenBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPBoPhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBoPhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPBoPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Bộ phận", jPanel2);

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuanLyPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuanLyPhongBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuanLyPhongBanActionPerformed

    private void btnAddPBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPBMouseEntered
        btnAddPB.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_btnAddPBMouseEntered

    private void btnAddPBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPBMouseExited
       setWhiteColor();
    }//GEN-LAST:event_btnAddPBMouseExited

    private void btnUpdatePBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdatePBMouseEntered
        btnUpdatePB.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_btnUpdatePBMouseEntered

    private void btnUpdatePBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdatePBMouseExited
       setWhiteColor();
    }//GEN-LAST:event_btnUpdatePBMouseExited

    private void btnResetPBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetPBMouseEntered
        btnResetPB.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_btnResetPBMouseEntered

    private void txtQuanLyBoPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuanLyBoPhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuanLyBoPhanActionPerformed

    private void btnAddBPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBPMouseEntered
        btnAddBP.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_btnAddBPMouseEntered

    private void btnAddBPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBPMouseExited
        setWhiteColor();
    }//GEN-LAST:event_btnAddBPMouseExited

    private void btnUpdateBPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateBPMouseEntered
        btnUpdateBP.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_btnUpdateBPMouseEntered

    private void btnUpdateBPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateBPMouseExited
        setWhiteColor();
    }//GEN-LAST:event_btnUpdateBPMouseExited

    private void btnResetBPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetBPMouseEntered
        btnResetBP.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_btnResetBPMouseEntered

    private void btnResetBPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetBPMouseExited
       setWhiteColor();
    }//GEN-LAST:event_btnResetBPMouseExited

    private void btnResetPBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetPBMouseExited
        setWhiteColor();
    }//GEN-LAST:event_btnResetPBMouseExited

    private void cbMaBP_BPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaBP_BPActionPerformed
        // TODO add your handling code here:
        String maBP = cbMaBP_BP.getSelectedItem().toString();
        if(maBP.equals("")){
            
        }else{
            Model.BoPhan bp = bpDAO.getBoPhanByMaBP(maBP);
            txtTenBP.setText(bp.getTenBP());
            txtGhiChu_BP.setText(bp.getGhiChu());
        }
    }//GEN-LAST:event_cbMaBP_BPActionPerformed

    private void btnAddBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBPActionPerformed
        // TODO add your handling code here:
        String tenBP = txtTenBP.getText();
        String ghiChu = txtGhiChu_BP.getText();
        if(bpDAO.isTenBPExists(tenBP)){
            JOptionPane.showMessageDialog(null, "Tên bộ phận đã tồn tại!");
        }else{
            if(Phantichthietkehethong_nhom4.kiemTraRong(jPBoPhan,cbMaBP_BP)){
                bpDAO.themBP(tenBP, ghiChu);
                
                JOptionPane.showMessageDialog(null, "Thêm thành công!");
                
                BPList = bpDAO.getBPList();
                loadDataToTableBP(BPList);
                loadMaBPToCB_BP();
                
                //reset form
                Phantichthietkehethong_nhom4.resetForm(jPBoPhan);
                txtQuanLyBoPhan.setText("Quản lý bộ phận");
            }else{
                JOptionPane.showMessageDialog(null, "Bạn chưa điền đầy đủ thông tin!");
            }
        }
    }//GEN-LAST:event_btnAddBPActionPerformed

    private void btnResetBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetBPActionPerformed
        // TODO add your handling code here:
        Phantichthietkehethong_nhom4.resetForm(jPBoPhan);
        txtQuanLyBoPhan.setText("Quản lý bộ phận");
    }//GEN-LAST:event_btnResetBPActionPerformed

    private void btnUpdatePBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePBActionPerformed
        // TODO add your handling code here:
        if(Phantichthietkehethong_nhom4.kiemTraRong(jPPB)){
            try{
                String maPB = cbMaPB_PB.getSelectedItem().toString();
                if(maPB.equals("")){
                    JOptionPane.showMessageDialog(null, "Bạn chưa chọn mã Phòng ban!");
                }else{
                    String tenPB = txtTenPB_PB.getText();
                    String ghiChu = txtGhiChu_PB.getText();
                    pbDAO.suaPB(tenPB,ghiChu,maPB);

                    JOptionPane.showMessageDialog(null, "Update thành công!");

                    PBList = pbDAO.getPBList();
                    loadDataToTablePB(PBList);
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Error!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "SQL error: "+ e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }catch(Exception j){
                JOptionPane.showMessageDialog(null, "Error: " + j.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(panelGradient1, "Bạn chưa nhập đủ thông tin!");
        }
    }//GEN-LAST:event_btnUpdatePBActionPerformed

    private void btnResetPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPBActionPerformed
        // TODO add your handling code here:
        Phantichthietkehethong_nhom4.resetForm(jPPB);
        txtQuanLyPhongBan.setText("Quản lý phòng ban");
        PBList = pbDAO.getPBList();
        loadDataToTablePB(PBList);
    }//GEN-LAST:event_btnResetPBActionPerformed

    private void btnUpdateBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBPActionPerformed
        // TODO add your handling code here:
        String maBP = cbMaBP_BP.getSelectedItem().toString();
        if(maBP.equals("")){
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn mã bộ phận!");
        }else{
            String tenBP = txtTenBP.getText();
            String ghiChu = txtGhiChu_BP.getText();
            bpDAO.suaBP(maBP, tenBP, ghiChu);
            
            JOptionPane.showMessageDialog(null, "Update thành công!");

            BPList = bpDAO.getBPList();
            loadDataToTableBP(BPList);
        }
    }//GEN-LAST:event_btnUpdateBPActionPerformed

    private void btnAddPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPBActionPerformed
        // TODO add your handling code here:
        String tenPB = txtTenPB_PB.getText();
        String ghiChu = txtGhiChu_PB.getText();
        String maBP = cbMaBP_PB.getSelectedItem().toString();
        txtQuanLyPhongBan.setText("Quản lý phòng ban");
        if(pbDAO.isTenPBExists(tenPB)){
            JOptionPane.showMessageDialog(null, "Tên phòng ban đã tồn tại!");
        }else{
            if(Phantichthietkehethong_nhom4.kiemTraRong(jPPB,cbMaPB_PB)){
                pbDAO.themPB(maBP,tenPB, ghiChu);
                
                JOptionPane.showMessageDialog(null, "Thêm thành công!");

                
                PBList = pbDAO.getPBList();
                loadDataToTablePB(PBList);
                loadMaPBTo_PB();
                
                //reset form
                Phantichthietkehethong_nhom4.resetForm(jPPB);
                
            }else{
                JOptionPane.showMessageDialog(null, "Bạn chưa điền đầy đủ thông tin!");
            }
        }
    }//GEN-LAST:event_btnAddPBActionPerformed

    private void clickToGetDataPB(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickToGetDataPB
        // TODO add your handling code here:
        int row = tbQuanLyPhongBan.getSelectedRow();
        if(row>=0){
//            PhongBanDAO pbDAO = new PhongBanDAO();
//            String tenPB = tbQuanLyPhongBan.getValueAt(row, 2).toString();
//            String maPB = pbDAO.getMaPBByTenPB(tenPB);
//            cbMaPB_PB.setSelectedItem(maPB);
            cbMaBP_PB.setSelectedItem(tbQuanLyPhongBan.getValueAt(row, 1).toString());
            cbMaPB_PB.setSelectedItem(tbQuanLyPhongBan.getValueAt(row, 0).toString());
//            cbMaBP_PB.setSelectedItem(tbQuanLyPhongBan.getValueAt(row, 1).toString());
            txtTenPB_PB.setText(tbQuanLyPhongBan.getValueAt(row, 2).toString());
            txtGhiChu_PB.setText(tbQuanLyPhongBan.getValueAt(row, 4).toString());
        }
    }//GEN-LAST:event_clickToGetDataPB

    private void clickToGetDataBP(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickToGetDataBP
        // TODO add your handling code here:
        int row = tbQuanLyBoPhan.getSelectedRow();
        if(row>=0){
            cbMaBP_BP.setSelectedItem(tbQuanLyBoPhan.getValueAt(row, 0).toString());
            txtTenBP.setText(tbQuanLyBoPhan.getValueAt(row, 1).toString());
            txtGhiChu_BP.setText(tbQuanLyBoPhan.getValueAt(row, 3).toString());
        }
    }//GEN-LAST:event_clickToGetDataBP

    private void cbMaBP_PBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaBP_PBActionPerformed
        // TODO add your handling code here:
        String maBP = cbMaBP_PB.getSelectedItem().toString();
        List<String> maPBList = pbDAO.getMaPBListByMaBP(maBP);
        
        loadMaPBToCB_PB(maPBList);
        safetySelectedCB(cbMaPB_PB);
    }//GEN-LAST:event_cbMaBP_PBActionPerformed

    private void cbMaPB_PBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaPB_PBActionPerformed
        // TODO add your handling code here:
        String maPB = cbMaPB_PB.getSelectedItem().toString();
        if(maPB.equals("")){

        }else{
            Model.PhongBan pb = pbDAO.getPhongBanByMaPB(maPB);
            cbMaBP_PB.setSelectedItem(maPB);
            txtTenPB_PB.setText(pb.getTenPB());
            txtGhiChu_PB.setText(pb.getGhiChu());
        }
    }//GEN-LAST:event_cbMaPB_PBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.ButtonGradient btnAddBP;
    private util.ButtonGradient btnAddPB;
    private util.ButtonGradient btnResetBP;
    private util.ButtonGradient btnResetPB;
    private util.ButtonGradient btnUpdateBP;
    private util.ButtonGradient btnUpdatePB;
    private javax.swing.JComboBox<String> cbMaBP_BP;
    private javax.swing.JComboBox<String> cbMaBP_PB;
    private javax.swing.JComboBox<String> cbMaPB_PB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPBoPhan;
    private javax.swing.JPanel jPPB;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private util.PanelGradient panelGradient1;
    private javax.swing.JTable tbQuanLyBoPhan;
    private javax.swing.JTable tbQuanLyPhongBan;
    private javax.swing.JTextArea txtGhiChu_BP;
    private javax.swing.JTextField txtGhiChu_PB;
    public static javax.swing.JTextField txtQuanLyBoPhan;
    public static javax.swing.JTextField txtQuanLyPhongBan;
    private javax.swing.JTextField txtTenBP;
    private javax.swing.JTextField txtTenPB_PB;
    // End of variables declaration//GEN-END:variables
}
