/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Quanly;

import DAO.NghiPhepDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class NghiPhep extends javax.swing.JPanel {

    /**
     * Creates new form NghiPhep
     */
    
    private NghiPhepDAO npDAO;
    private List<Model.NghiPhep> NPList;
    private int maNP;
    
    public NghiPhep() {
        initComponents();
        npDAO = new NghiPhepDAO();
        NPList = new ArrayList<>();
        NPList = npDAO.getNPList();
        
        //Load data lên bảng
        loadDataToTableNP(NPList);
    }
    
    public void loadDataToTableNP(List<Model.NghiPhep> NPList){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã nghỉ phép");
        dtm.addColumn("Mã nhân viên");
        dtm.addColumn("Họ tên");
        dtm.addColumn("Lý do");
        dtm.addColumn("Ngày bắt đầu");
        dtm.addColumn("Ngày kết thúc");
        dtm.addColumn("Trạng thái");
        
        Object[] row = new Object[7];
        for(Model.NghiPhep np: NPList){
            row[0] = np.getMaNghiPhep();
            row[1] = np.getMaNV();
            row[2] = np.getHoTen();
            row[3] = np.getLyDo();
            row[4] = np.getNgayBatDau();
            row[5] = np.getNgayKetThuc();
            row[6] = np.getTrangThai();
            dtm.addRow(row);
        }
        tblQuanLyNghiPhep.setModel(dtm);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new util.PanelGradient();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuanLyNghiPhep = new javax.swing.JTable();
        btnDuyet_NP = new util.ButtonGradient();
        btnTuChoi = new util.ButtonGradient();
        txtQuanLyNghiPhep = new javax.swing.JTextField();

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblQuanLyNghiPhep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblQuanLyNghiPhep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickToGetDataNP(evt);
            }
        });
        jScrollPane1.setViewportView(tblQuanLyNghiPhep);

        btnDuyet_NP.setText("Duyệt");
        btnDuyet_NP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDuyet_NP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDuyet_NPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDuyet_NPMouseExited(evt);
            }
        });
        btnDuyet_NP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuyet_NPActionPerformed(evt);
            }
        });

        btnTuChoi.setText("Từ chối");
        btnTuChoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTuChoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTuChoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTuChoiMouseExited(evt);
            }
        });
        btnTuChoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuChoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(btnDuyet_NP, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(btnTuChoi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDuyet_NP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTuChoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        txtQuanLyNghiPhep.setBackground(new java.awt.Color(0, 153, 153));
        txtQuanLyNghiPhep.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQuanLyNghiPhep.setText("Quản lý nghỉ phép");
        txtQuanLyNghiPhep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuanLyNghiPhepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtQuanLyNghiPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtQuanLyNghiPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nghỉ phép", jPanel1);

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuanLyNghiPhepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuanLyNghiPhepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuanLyNghiPhepActionPerformed

    private void btnDuyet_NPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDuyet_NPMouseEntered
        btnDuyet_NP.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_btnDuyet_NPMouseEntered

    private void btnDuyet_NPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDuyet_NPMouseExited
         btnDuyet_NP.setForeground(Color.white);
    }//GEN-LAST:event_btnDuyet_NPMouseExited

    private void btnDuyet_NPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuyet_NPActionPerformed
        // TODO add your handling code here:
        int row = tblQuanLyNghiPhep.getSelectedRow();
        if(row>=0){
            String trangThai = (tblQuanLyNghiPhep.getValueAt(row, 6).toString());
            if(trangThai.equalsIgnoreCase("Chưa xác nhận")){
                //nếu chưa xác nhận thì được duyệt
                npDAO.duyetNghiPhep(maNP);
                NPList = npDAO.getNPList();
                loadDataToTableNP(NPList);
            }else{
                //nếu không thì không được duyệt
                JOptionPane.showMessageDialog(panelGradient1, "Nghỉ phép đã được duyệt, không thể thay đổi!");
            }
        }
    }//GEN-LAST:event_btnDuyet_NPActionPerformed

    private void clickToGetDataNP(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickToGetDataNP
        // TODO add your handling code here:
        int row = tblQuanLyNghiPhep.getSelectedRow();
        if(row>=0){
            maNP = (int)tblQuanLyNghiPhep.getValueAt(row, 0);
        }
    }//GEN-LAST:event_clickToGetDataNP

    private void btnTuChoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTuChoiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTuChoiMouseEntered

    private void btnTuChoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTuChoiMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTuChoiMouseExited

    private void btnTuChoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuChoiActionPerformed
        // TODO add your handling code here:
        
        int row = tblQuanLyNghiPhep.getSelectedRow();
        if(row>=0){
            String trangThai = (tblQuanLyNghiPhep.getValueAt(row, 6).toString());
            if(trangThai.equalsIgnoreCase("Chưa xác nhận")){
                //nếu chưa xác nhận thì được từ chối
                npDAO.tuChoiNghiPhep(maNP);
                NPList = npDAO.getNPList();
                loadDataToTableNP(NPList);
            }else{
                //nếu không thì không được từ chối
                JOptionPane.showMessageDialog(panelGradient1, "Nghỉ phép đã được duyệt, không thể từ chối!");
            }
        }
    }//GEN-LAST:event_btnTuChoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.ButtonGradient btnDuyet_NP;
    private util.ButtonGradient btnTuChoi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private util.PanelGradient panelGradient1;
    private javax.swing.JTable tblQuanLyNghiPhep;
    public static javax.swing.JTextField txtQuanLyNghiPhep;
    // End of variables declaration//GEN-END:variables
}
