/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Quanly;

import DAO.NVDAO;
import Model.NhanVien;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import PTPM_NHOM18.PTPM_NHOM18;

/**
 *
 * @author Admin
 */
public class TraCuuThongTin extends javax.swing.JPanel {

    /**
     * Creates new form TraCuuThongTin
     */
    
    private final NVDAO nvDAO;
    private final List<NhanVien> NVList;
    
    public TraCuuThongTin() {
        initComponents();
        nvDAO = new NVDAO();
        NVList = nvDAO.getNVList();
        
        //load data lên bảng
        loadDataToTableNV(NVList);
    }
    
    private void adjustColumnWidths(JTable myTable){
        // Giả sử bảng của bạn có tên là "yourTableName"
        JTable table = myTable;

        // Lấy mô hình cột của bảng
        TableColumnModel columnModel = table.getColumnModel();

        // Lặp qua tất cả các cột để đặt chiều rộng nếu cần thiết
        for (int i = 0; i < columnModel.getColumnCount(); i++) {
            TableColumn column = columnModel.getColumn(i);
            column.setPreferredWidth(120); // Bạn có thể tùy chỉnh giá trị này
        }

    }
    
    private void loadDataToTableNV(List<NhanVien> NVList){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã nhân viên");
        dtm.addColumn("Họ tên");
        dtm.addColumn("Giới tính");
        dtm.addColumn("Dân tộc");
        dtm.addColumn("Chức vụ");
        dtm.addColumn("Loại hợp đồng");
        dtm.addColumn("Ngày đăng kí");
        dtm.addColumn("Thời gian");
        dtm.addColumn("CMND_CCCD");
        dtm.addColumn("SDT");
        dtm.addColumn("Học vấn");
        dtm.addColumn("Email");
        dtm.addColumn("Mã phòng ban");
        dtm.addColumn("Mã lương");
        dtm.addColumn("Ghi chú");
        
        
        Object[] row = new Object[15];
        for(NhanVien nv: NVList){
            row[0] = nv.getMaNV();
            row[1] = nv.getHoTen();
            row[2] = nv.getGioiTinh();
            row[3] = nv.getDanToc();
            row[4] = nv.getChucVu();
            row[5] = nv.getLoaiHopDong();
            row[6] = nv.getNgayDangKy();
            row[7] = nv.getThoiGian();
            row[8] = nv.getCMND_CCCD();
            row[9] = nv.getSDT();
            row[10] = nv.getHocVan();
            row[11] = nv.getEmail();
            row[12] = nv.getMaPB();
            row[13] = nv.getMaLuong();
            row[14] = nv.getGhiChu();
            dtm.addRow(row);
        }
        tblTraCuuThongTin.setModel(dtm);
        
        adjustColumnWidths(tblTraCuuThongTin);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelGradient1 = new util.PanelGradient();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPTraCuuTT = new javax.swing.JPanel();
        txtTraCuuThongTin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTraCuuThongTin = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNhapThongTin = new javax.swing.JTextField();
        rbtMaNhanVien = new javax.swing.JRadioButton();
        rbtHoVaTen = new javax.swing.JRadioButton();
        rbtSoDienThoai = new javax.swing.JRadioButton();
        btnReset = new util.ButtonGradient();
        btnTimKiem = new util.ButtonGradient();

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtTraCuuThongTin.setBackground(new java.awt.Color(0, 153, 153));
        txtTraCuuThongTin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTraCuuThongTin.setText("Tra cứu thông tin");
        txtTraCuuThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTraCuuThongTinActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblTraCuuThongTin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTraCuuThongTin.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblTraCuuThongTin.setMinimumSize(new java.awt.Dimension(100, 80));
        jScrollPane1.setViewportView(tblTraCuuThongTin);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Thông tin");

        txtNhapThongTin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtNhapThongTin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(rbtMaNhanVien);
        rbtMaNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        rbtMaNhanVien.setText("Mã nhân viên");
        rbtMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMaNhanVienActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtHoVaTen);
        rbtHoVaTen.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        rbtHoVaTen.setText("Họ và tên");

        buttonGroup1.add(rbtSoDienThoai);
        rbtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        rbtSoDienThoai.setText("Số điện thoại");

        btnReset.setText("Làm mới");
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetMouseExited(evt);
            }
        });
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseExited(evt);
            }
        });
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTraCuuTTLayout = new javax.swing.GroupLayout(jPTraCuuTT);
        jPTraCuuTT.setLayout(jPTraCuuTTLayout);
        jPTraCuuTTLayout.setHorizontalGroup(
            jPTraCuuTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTraCuuTTLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288))
            .addGroup(jPTraCuuTTLayout.createSequentialGroup()
                .addGroup(jPTraCuuTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTraCuuTTLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(rbtMaNhanVien)
                        .addGap(168, 168, 168)
                        .addComponent(rbtHoVaTen)
                        .addGap(178, 178, 178)
                        .addComponent(rbtSoDienThoai))
                    .addGroup(jPTraCuuTTLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(txtNhapThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPTraCuuTTLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPTraCuuTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTraCuuThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPTraCuuTTLayout.setVerticalGroup(
            jPTraCuuTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTraCuuTTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTraCuuThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPTraCuuTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNhapThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPTraCuuTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtMaNhanVien)
                    .addComponent(rbtHoVaTen)
                    .addComponent(rbtSoDienThoai))
                .addGap(37, 37, 37)
                .addGroup(jPTraCuuTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tra cứu thông tin", jPTraCuuTT);

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTraCuuThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTraCuuThongTinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTraCuuThongTinActionPerformed

    private void rbtMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtMaNhanVienActionPerformed

    private void btnTimKiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseEntered
       btnTimKiem.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_btnTimKiemMouseEntered

    private void btnTimKiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseExited
        btnTimKiem.setForeground(Color.white);
    }//GEN-LAST:event_btnTimKiemMouseExited

    private void btnResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseEntered
        btnReset.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_btnResetMouseEntered

    private void btnResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseExited
        btnReset.setForeground(Color.white);
    }//GEN-LAST:event_btnResetMouseExited

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        PTPM_NHOM18.resetForm(jPTraCuuTT);
        loadDataToTableNV(NVList);
        txtTraCuuThongTin.setText("Tra cứu thông tin");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        if(PTPM_NHOM18.kiemTraRong(jPTraCuuTT)){
            String ttin = txtNhapThongTin.getText().toLowerCase();
            List<NhanVien> NVTam = new ArrayList<>();
            if(rbtMaNhanVien.isSelected()){
                for(NhanVien nv: NVList){
                    if(nv.getMaNV().contains(ttin)){
                        NVTam.add(nv);
                    }
                }
                loadDataToTableNV(NVTam);
            }else if(rbtHoVaTen.isSelected()){
                for(NhanVien nv: NVList){
                    if(nv.getHoTen().toLowerCase().contains(ttin)){
                        NVTam.add(nv);
                    }
                }
                loadDataToTableNV(NVTam);
            }else if(rbtSoDienThoai.isSelected()){
                for(NhanVien nv: NVList){
                    if(nv.getSDT().equals(ttin)){
                        NVTam.add(nv);
                    }
                }
                loadDataToTableNV(NVTam);
            }
        }else{
            JOptionPane.showMessageDialog(panelGradient1, "Bạn chưa nhập thông tin tìm kiếm!");
        }
        
    }//GEN-LAST:event_btnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.ButtonGradient btnReset;
    private util.ButtonGradient btnTimKiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPTraCuuTT;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private util.PanelGradient panelGradient1;
    private javax.swing.JRadioButton rbtHoVaTen;
    private javax.swing.JRadioButton rbtMaNhanVien;
    private javax.swing.JRadioButton rbtSoDienThoai;
    private javax.swing.JTable tblTraCuuThongTin;
    private javax.swing.JTextField txtNhapThongTin;
    public static javax.swing.JTextField txtTraCuuThongTin;
    // End of variables declaration//GEN-END:variables
}
