/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ChucNang_QL_ChamCong;

import DAO.NVThuViecDAO;
import DAO.TinhLuongTVDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import phantichthietkehethong_nhom4.Phantichthietkehethong_nhom4;

/**
 *
 * @author Admin
 */
public class ChamCongNhanVienThuViec extends javax.swing.JFrame {

    /**
     * Creates new form ChamCongNhanVienThuViec
     */
    private final Quanly.ChamCong CCForm;
    private final NVThuViecDAO nvThuViecDAO;
    private final TinhLuongTVDAO tinhLuongTVDAO;
    
    public ChamCongNhanVienThuViec(Quanly.ChamCong ccform) {
        initComponents();
        this.CCForm = ccform;
        nvThuViecDAO = new NVThuViecDAO();
        tinhLuongTVDAO = new TinhLuongTVDAO();
        loadMaKTToCB_CC();
        tfLuong_CCThuViec.setEditable(false);
    }
    
    private void setWhiteColor()
    {
        bttThem_CCThuViec.setForeground(Color.white);
        bttHuy_CCThuViec.setForeground(Color.white);    
    }
    private void loadMaKTToCB_CC(){
        List<String> maNVTVList = new ArrayList<>();
        maNVTVList = nvThuViecDAO.getListMaNVTV();
        DefaultComboBoxModel<String> model_nv = new DefaultComboBoxModel<>(maNVTVList.toArray(new String[0]));
        cb_maNVTV_CCTV.setModel(model_nv);
    }
    
    private void reLoadData(){
        List<Model.TinhLuongTV> ltvList = new ArrayList<>();
        ltvList = tinhLuongTVDAO.getListTinhLuongTV();
        CCForm.loadDataToTableTLTV(ltvList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCCNVTV = new util.PanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfSoGioThem_CCThuViec = new javax.swing.JTextField();
        tfSoNgayCong_CCThuViec = new javax.swing.JTextField();
        tfGhiChu_CCThuViec = new javax.swing.JTextField();
        tfLuong_CCThuViec = new javax.swing.JTextField();
        cbThang_CCThuViec = new javax.swing.JComboBox<>();
        cbNam_CCThuViec = new javax.swing.JComboBox<>();
        bttThem_CCThuViec = new util.ButtonGradient();
        bttHuy_CCThuViec = new util.ButtonGradient();
        cb_maNVTV_CCTV = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Chấm công nhân viên thử việc");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Số ngày công");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Mã nhân viên");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Tháng");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Lương thử việc");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Ghi chú");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Số giờ thêm");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Năm");

        tfSoGioThem_CCThuViec.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfSoGioThem_CCThuViec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfSoNgayCong_CCThuViec.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfSoNgayCong_CCThuViec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfGhiChu_CCThuViec.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfGhiChu_CCThuViec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfLuong_CCThuViec.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfLuong_CCThuViec.setText("0");
        tfLuong_CCThuViec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbThang_CCThuViec.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbThang_CCThuViec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbThang_CCThuViec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbNam_CCThuViec.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbNam_CCThuViec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014" }));
        cbNam_CCThuViec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bttThem_CCThuViec.setText("Thêm");
        bttThem_CCThuViec.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttThem_CCThuViec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttThem_CCThuViecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttThem_CCThuViecMouseExited(evt);
            }
        });
        bttThem_CCThuViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttThem_CCThuViecActionPerformed(evt);
            }
        });

        bttHuy_CCThuViec.setText("Hủy");
        bttHuy_CCThuViec.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttHuy_CCThuViec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttHuy_CCThuViecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttHuy_CCThuViecMouseExited(evt);
            }
        });
        bttHuy_CCThuViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttHuy_CCThuViecActionPerformed(evt);
            }
        });

        cb_maNVTV_CCTV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_maNVTV_CCTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_maNVTV_CCTVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCCNVTVLayout = new javax.swing.GroupLayout(pnCCNVTV);
        pnCCNVTV.setLayout(pnCCNVTVLayout);
        pnCCNVTVLayout.setHorizontalGroup(
            pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCCNVTVLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(186, 186, 186))
            .addGroup(pnCCNVTVLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCCNVTVLayout.createSequentialGroup()
                        .addGroup(pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnCCNVTVLayout.createSequentialGroup()
                                .addComponent(tfLuong_CCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel7))
                            .addGroup(pnCCNVTVLayout.createSequentialGroup()
                                .addGroup(pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbThang_CCThuViec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbNam_CCThuViec, 0, 191, Short.MAX_VALUE)
                                    .addComponent(cb_maNVTV_CCTV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSoNgayCong_CCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSoGioThem_CCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGhiChu_CCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnCCNVTVLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bttThem_CCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(bttHuy_CCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnCCNVTVLayout.setVerticalGroup(
            pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCCNVTVLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(tfSoNgayCong_CCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCCNVTVLayout.createSequentialGroup()
                        .addComponent(cb_maNVTV_CCTV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGroup(pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCCNVTVLayout.createSequentialGroup()
                        .addGroup(pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnCCNVTVLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel5))
                            .addComponent(cbThang_CCThuViec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnCCNVTVLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel9))
                            .addGroup(pnCCNVTVLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cbNam_CCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnCCNVTVLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(tfSoGioThem_CCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGhiChu_CCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLuong_CCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(pnCCNVTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttThem_CCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttHuy_CCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCCNVTV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCCNVTV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttThem_CCThuViecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttThem_CCThuViecMouseEntered
        bttThem_CCThuViec.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttThem_CCThuViecMouseEntered

    private void bttThem_CCThuViecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttThem_CCThuViecMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttThem_CCThuViecMouseExited

    private void bttHuy_CCThuViecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_CCThuViecMouseEntered
        bttHuy_CCThuViec.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttHuy_CCThuViecMouseEntered

    private void bttHuy_CCThuViecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_CCThuViecMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttHuy_CCThuViecMouseExited

    private void bttHuy_CCThuViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttHuy_CCThuViecActionPerformed
        setVisible(false);
//        ChamCong.btnReset_CCTV.setEnabled(true);
    }//GEN-LAST:event_bttHuy_CCThuViecActionPerformed

    private void cb_maNVTV_CCTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_maNVTV_CCTVActionPerformed
        // TODO add your handling code here:
        String maNVTV = cb_maNVTV_CCTV.getSelectedItem().toString();
        int luong = nvThuViecDAO.getLuongTVByMaNVTV(maNVTV);
        tfLuong_CCThuViec.setText(String.valueOf(luong));
    }//GEN-LAST:event_cb_maNVTV_CCTVActionPerformed

    private void bttThem_CCThuViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttThem_CCThuViecActionPerformed
        // TODO add your handling code here:
        if(phantichthietkehethong_nhom4.Phantichthietkehethong_nhom4.kiemTraRong(pnCCNVTV)== false){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin");
        }
        else{
            String maNhanVien = cb_maNVTV_CCTV.getSelectedItem().toString();
            String maLuongTV = nvThuViecDAO.getMaLuongTVByMaNVTV(maNhanVien);
            int thang;
            int nam;
            int luongThuViec;
            int soNgayCong;
            int soGioLamThem;
            int luongThucNhan;
            String ghiChu = tfGhiChu_CCThuViec.getText();
            
            try{
                thang = Integer.parseInt(cbThang_CCThuViec.getSelectedItem().toString());
                nam = Integer.parseInt(cbNam_CCThuViec.getSelectedItem().toString());
                luongThuViec = Integer.parseInt(tfLuong_CCThuViec.getText());
                soNgayCong = Integer.parseInt(tfSoNgayCong_CCThuViec.getText());
                soGioLamThem = Integer.parseInt(tfSoGioThem_CCThuViec.getText());
                luongThucNhan = luongThuViec  + (soGioLamThem*50000);
                
                tinhLuongTVDAO.addTinhLuongTV(maNhanVien, maLuongTV, thang, nam, luongThuViec, soNgayCong, soGioLamThem, luongThucNhan, ghiChu);
                Phantichthietkehethong_nhom4.resetForm(pnCCNVTV);
                
                reLoadData();
                
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Error: Nhập sai định dạng!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            }catch(Exception j){
                JOptionPane.showMessageDialog(null, "Error: " + j.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bttThem_CCThuViecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChamCongNhanVienThuViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChamCongNhanVienThuViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChamCongNhanVienThuViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChamCongNhanVienThuViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.ButtonGradient bttHuy_CCThuViec;
    private util.ButtonGradient bttThem_CCThuViec;
    private javax.swing.JComboBox<String> cbNam_CCThuViec;
    private javax.swing.JComboBox<String> cbThang_CCThuViec;
    private javax.swing.JComboBox<String> cb_maNVTV_CCTV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private util.PanelGradient pnCCNVTV;
    private javax.swing.JTextField tfGhiChu_CCThuViec;
    private javax.swing.JTextField tfLuong_CCThuViec;
    private javax.swing.JTextField tfSoGioThem_CCThuViec;
    private javax.swing.JTextField tfSoNgayCong_CCThuViec;
    // End of variables declaration//GEN-END:variables
}
