/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ChucNang_QL_ChamCong;

import DAO.DuAnDAO;
import DAO.LuongDAO;
import DAO.NVDAO;
import DAO.PhongBanDAO;
import Model.NhanVien;
import static Quanly.ChamCong.txtMaPhong_CC;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ChonNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form ChonNhanVien
     */
    private List<NhanVien> ListNV;
    private NVDAO nhanVienDAO;
    private LuongDAO luongDAO;
    private DuAnDAO duanDAO;
    private PhongBanDAO phongBanDAO;
    private Quanly.ChamCong CCform;
    public ChonNhanVien(Quanly.ChamCong CCform) {
        initComponents();
        ListNV = new ArrayList<>();
        nhanVienDAO = new NVDAO();
        phongBanDAO = new PhongBanDAO();
        luongDAO = new LuongDAO();
        duanDAO = new DuAnDAO();
        ListNV = nhanVienDAO.getNVList();
        loadDataToTable(ListNV);
        this.CCform = CCform;
        tfMaNhanVien_ChonNhanVien.setEditable(false);
        tfHoTen_ChonNhanVien.setEditable(false);
        tfSoCCCD_ChonNhanVien.setEditable(false);
        tfPhong_ChonNhanVien.setEditable(false);
    }
    
     private void setWhiteColor()
    {
        bttHoanThanh_ChonNhanVien.setForeground(Color.white);
        bttHuy_ChonNhanVien.setForeground(Color.white);           
    }
    private void loadDataToTable(List<NhanVien> ListNV){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã nhân viên");
        dtm.addColumn("Họ tên");
        dtm.addColumn("CCCD");
        dtm.addColumn("Phòng ban");
        Object[] row = new Object[4];
        for(Model.NhanVien nv : ListNV){
            row[0] = nv.getMaNV();
            row[1] = nv.getHoTen();
            row[2] = nv.getCMND_CCCD();
            row[3] = phongBanDAO.getTenPhongBanByMaNV(nv.getMaNV());
            dtm.addRow(row);
        }
        tbl_ChonNhanVien.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new util.PanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ChonNhanVien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfMaNhanVien_ChonNhanVien = new javax.swing.JTextField();
        tfHoTen_ChonNhanVien = new javax.swing.JTextField();
        tfSoCCCD_ChonNhanVien = new javax.swing.JTextField();
        tfPhong_ChonNhanVien = new javax.swing.JTextField();
        bttHoanThanh_ChonNhanVien = new util.ButtonGradient();
        bttHuy_ChonNhanVien = new util.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Chọn nhân viên");

        tbl_ChonNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_ChonNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ChonNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ChonNhanVien);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mã nhân viên");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Họ tên");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Phòng");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Số CCCD");

        tfMaNhanVien_ChonNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfMaNhanVien_ChonNhanVien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfHoTen_ChonNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfHoTen_ChonNhanVien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfSoCCCD_ChonNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfSoCCCD_ChonNhanVien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfPhong_ChonNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfPhong_ChonNhanVien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bttHoanThanh_ChonNhanVien.setText("Hoàn thành");
        bttHoanThanh_ChonNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttHoanThanh_ChonNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttHoanThanh_ChonNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttHoanThanh_ChonNhanVienMouseExited(evt);
            }
        });
        bttHoanThanh_ChonNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttHoanThanh_ChonNhanVienActionPerformed(evt);
            }
        });

        bttHuy_ChonNhanVien.setText("Hủy");
        bttHuy_ChonNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttHuy_ChonNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttHuy_ChonNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttHuy_ChonNhanVienMouseExited(evt);
            }
        });
        bttHuy_ChonNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttHuy_ChonNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMaNhanVien_ChonNhanVien)
                            .addComponent(tfHoTen_ChonNhanVien)
                            .addComponent(tfSoCCCD_ChonNhanVien)
                            .addComponent(tfPhong_ChonNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bttHoanThanh_ChonNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(bttHuy_ChonNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(92, 92, 92))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(342, 342, 342))
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(tfMaNhanVien_ChonNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfHoTen_ChonNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfSoCCCD_ChonNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfPhong_ChonNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(bttHoanThanh_ChonNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttHuy_ChonNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttHoanThanh_ChonNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHoanThanh_ChonNhanVienMouseEntered
        bttHoanThanh_ChonNhanVien.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttHoanThanh_ChonNhanVienMouseEntered

    private void bttHoanThanh_ChonNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHoanThanh_ChonNhanVienMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttHoanThanh_ChonNhanVienMouseExited

    private void bttHuy_ChonNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_ChonNhanVienMouseEntered
        bttHuy_ChonNhanVien.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttHuy_ChonNhanVienMouseEntered

    private void bttHuy_ChonNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_ChonNhanVienMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttHuy_ChonNhanVienMouseExited

    private void bttHuy_ChonNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttHuy_ChonNhanVienActionPerformed
        setVisible(false);
    }//GEN-LAST:event_bttHuy_ChonNhanVienActionPerformed

    private void tbl_ChonNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ChonNhanVienMouseClicked
        // TODO add your handling code here:
        int row = tbl_ChonNhanVien.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) tbl_ChonNhanVien.getModel();
        String maNV = dtm.getValueAt(row, 0).toString();
        String hoTen = dtm.getValueAt(row, 1).toString();
        String CCCD = dtm.getValueAt(row, 2).toString();
        String phongBan = dtm.getValueAt(row, 3).toString();
        tfMaNhanVien_ChonNhanVien.setText(maNV);
        tfHoTen_ChonNhanVien.setText(hoTen);
        tfSoCCCD_ChonNhanVien.setText(CCCD);
        tfPhong_ChonNhanVien.setText(phongBan);
    }//GEN-LAST:event_tbl_ChonNhanVienMouseClicked

    private void bttHoanThanh_ChonNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttHoanThanh_ChonNhanVienActionPerformed
        // TODO add your handling code here:
        String maNV = tfMaNhanVien_ChonNhanVien.getText();
        Model.NhanVien nv = nhanVienDAO.getNVByMaNV(maNV);
        Model.Luong luong = luongDAO.getLuongByMaNV(maNV);
        if(maNV.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn nhân viên!");
        }
        else{
            CCform.txtMaPhong_CC.setText(nv.getMaPB());
            CCform.txtMaLuong_CC.setText(nv.getMaLuong());  
            CCform.txtLuongCB_CC.setText(String.valueOf(luong.getLuongCoBan()));
            CCform.txtPCCV_CC.setText(Integer.toString(luong.getPhuCapCV()));
            CCform.txtPCK_CC.setText(Integer.toString(luong.getPhuCapKhac()));
            CCform.cbMaNV_CC.setSelectedItem(maNV);
            this.dispose();
        }
        
    }//GEN-LAST:event_bttHoanThanh_ChonNhanVienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChonNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChonNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChonNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChonNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //    new ChonNhanVien().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.ButtonGradient bttHoanThanh_ChonNhanVien;
    private util.ButtonGradient bttHuy_ChonNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private util.PanelGradient panelGradient1;
    private javax.swing.JTable tbl_ChonNhanVien;
    private javax.swing.JTextField tfHoTen_ChonNhanVien;
    private javax.swing.JTextField tfMaNhanVien_ChonNhanVien;
    private javax.swing.JTextField tfPhong_ChonNhanVien;
    private javax.swing.JTextField tfSoCCCD_ChonNhanVien;
    // End of variables declaration//GEN-END:variables
}
