/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ChucNang_QL_ChamCong;

import DAO.KyLuatDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class DanhSachKyLuat extends javax.swing.JFrame {

    /**
     * Creates new form DanhSachKyLuat
     */
    private KyLuatDAO kyLuatDAO;
    private List<Model.kyLuat> KyLuatList;
    private Quanly.ChamCong CCform;
    public DanhSachKyLuat(Quanly.ChamCong CCform) {
        initComponents();
        kyLuatDAO = new KyLuatDAO();
        KyLuatList = new ArrayList<>();
        KyLuatList = kyLuatDAO.getListKyLuat();
        loadDataToTableKL(KyLuatList);
        this.CCform = CCform;
        tfSoTien_DanhSachKyLuat.setEditable(false);
        tfTienSanCo_DanhSachKyLuat.setEditable(false);
        tfTongTien_DanhSachKyLuat.setEditable(false);
    }
    
    private void loadDataToTableKL(List<Model.kyLuat> kyLuatList){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã kỷ luật");
        dtm.addColumn("Tiền kỷ luật");
        dtm.addColumn("Lý do");
        
        Object[] row = new Object[3];
        for(Model.kyLuat kl : kyLuatList){
            row[0] = kl.getMaKyLuat();
            row[1] = kl.getTienKyLuat();
            row[2] = kl.getLyDo();
            dtm.addRow(row);
        }
        tbl_KyLuat.setModel(dtm);
    }
     private void setWhiteColor()
    {
        bttCongThem_DanhSachKyLuat.setForeground(Color.white);
        bttTruDi_DanhSachKyLuat.setForeground(Color.white);    
       
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new util.PanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_KyLuat = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfSoTien_DanhSachKyLuat = new javax.swing.JTextField();
        tfSoLan_DánhachKyLuat = new javax.swing.JTextField();
        tfTienSanCo_DanhSachKyLuat = new javax.swing.JTextField();
        tfTongTien_DanhSachKyLuat = new javax.swing.JTextField();
        bttCongThem_DanhSachKyLuat = new util.ButtonGradient();
        bttTruDi_DanhSachKyLuat = new util.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Danh sách kỷ luật");

        tbl_KyLuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_KyLuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KyLuatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_KyLuat);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Số tiền");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Số lần");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Tổng tiền");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Tiền sẵn có");

        tfSoTien_DanhSachKyLuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfSoTien_DanhSachKyLuat.setText("0");
        tfSoTien_DanhSachKyLuat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfSoTien_DanhSachKyLuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoTien_DanhSachKyLuatActionPerformed(evt);
            }
        });

        tfSoLan_DánhachKyLuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfSoLan_DánhachKyLuat.setText("0");
        tfSoLan_DánhachKyLuat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfSoLan_DánhachKyLuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoLan_DánhachKyLuatActionPerformed(evt);
            }
        });

        tfTienSanCo_DanhSachKyLuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfTienSanCo_DanhSachKyLuat.setText("0");
        tfTienSanCo_DanhSachKyLuat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfTongTien_DanhSachKyLuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfTongTien_DanhSachKyLuat.setText("0");
        tfTongTien_DanhSachKyLuat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bttCongThem_DanhSachKyLuat.setText("Cộng thêm");
        bttCongThem_DanhSachKyLuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttCongThem_DanhSachKyLuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttCongThem_DanhSachKyLuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttCongThem_DanhSachKyLuatMouseExited(evt);
            }
        });
        bttCongThem_DanhSachKyLuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCongThem_DanhSachKyLuatActionPerformed(evt);
            }
        });

        bttTruDi_DanhSachKyLuat.setText("Thoát");
        bttTruDi_DanhSachKyLuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttTruDi_DanhSachKyLuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttTruDi_DanhSachKyLuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttTruDi_DanhSachKyLuatMouseExited(evt);
            }
        });
        bttTruDi_DanhSachKyLuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttTruDi_DanhSachKyLuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSoTien_DanhSachKyLuat)
                            .addComponent(tfSoLan_DánhachKyLuat)
                            .addComponent(tfTienSanCo_DanhSachKyLuat)
                            .addComponent(tfTongTien_DanhSachKyLuat, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bttCongThem_DanhSachKyLuat, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(bttTruDi_DanhSachKyLuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(92, 92, 92))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(333, 333, 333))
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(tfSoTien_DanhSachKyLuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfSoLan_DánhachKyLuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfTienSanCo_DanhSachKyLuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfTongTien_DanhSachKyLuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(bttCongThem_DanhSachKyLuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttTruDi_DanhSachKyLuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttCongThem_DanhSachKyLuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttCongThem_DanhSachKyLuatMouseEntered
        bttCongThem_DanhSachKyLuat.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttCongThem_DanhSachKyLuatMouseEntered

    private void bttCongThem_DanhSachKyLuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttCongThem_DanhSachKyLuatMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttCongThem_DanhSachKyLuatMouseExited

    private void bttTruDi_DanhSachKyLuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttTruDi_DanhSachKyLuatMouseEntered
        bttTruDi_DanhSachKyLuat.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttTruDi_DanhSachKyLuatMouseEntered

    private void bttTruDi_DanhSachKyLuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttTruDi_DanhSachKyLuatMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttTruDi_DanhSachKyLuatMouseExited

    private void bttTruDi_DanhSachKyLuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttTruDi_DanhSachKyLuatActionPerformed
        CCform.txtKyLuat_CC.setText(tfTongTien_DanhSachKyLuat.getText());
        this.dispose();
    }//GEN-LAST:event_bttTruDi_DanhSachKyLuatActionPerformed

    private void bttCongThem_DanhSachKyLuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCongThem_DanhSachKyLuatActionPerformed
        int tienSanCo = Integer.parseInt(tfTienSanCo_DanhSachKyLuat.getText());
        int tongTien = Integer.parseInt(tfTongTien_DanhSachKyLuat.getText())+ tienSanCo;
        tfTongTien_DanhSachKyLuat.setText(String.valueOf(tongTien));
    }//GEN-LAST:event_bttCongThem_DanhSachKyLuatActionPerformed

    private void tbl_KyLuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KyLuatMouseClicked
        // TODO add your handling code here:
        int row = tbl_KyLuat.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) tbl_KyLuat.getModel();
        String tienThuong = dtm.getValueAt(row, 1).toString();
        tfSoTien_DanhSachKyLuat.setText(tienThuong);
        int soTien = Integer.parseInt(tfSoTien_DanhSachKyLuat.getText());
        int soLan = Integer.parseInt(tfSoLan_DánhachKyLuat.getText());
        int tienSanCo = soTien * soLan;
        tfTienSanCo_DanhSachKyLuat.setText(String.valueOf(tienSanCo));
    }//GEN-LAST:event_tbl_KyLuatMouseClicked

    private void tfSoLan_DánhachKyLuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoLan_DánhachKyLuatActionPerformed
        // TODO add your handling code here:
        int soTien = Integer.parseInt(tfSoTien_DanhSachKyLuat.getText());
        int soLan = Integer.parseInt(tfSoLan_DánhachKyLuat.getText());
        int tienSanCo = soTien * soLan;
        tfTienSanCo_DanhSachKyLuat.setText(String.valueOf(tienSanCo));
    }//GEN-LAST:event_tfSoLan_DánhachKyLuatActionPerformed

    private void tfSoTien_DanhSachKyLuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoTien_DanhSachKyLuatActionPerformed
        // TODO add your handling code here:
        int soTien = Integer.parseInt(tfSoTien_DanhSachKyLuat.getText());
        int soLan = Integer.parseInt(tfSoLan_DánhachKyLuat.getText());
        int tienSanCo = soTien * soLan;
        tfTienSanCo_DanhSachKyLuat.setText(String.valueOf(tienSanCo));
    }//GEN-LAST:event_tfSoTien_DanhSachKyLuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSachKyLuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSachKyLuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSachKyLuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachKyLuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DanhSachKyLuat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.ButtonGradient bttCongThem_DanhSachKyLuat;
    private util.ButtonGradient bttTruDi_DanhSachKyLuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private util.PanelGradient panelGradient1;
    private javax.swing.JTable tbl_KyLuat;
    private javax.swing.JTextField tfSoLan_DánhachKyLuat;
    private javax.swing.JTextField tfSoTien_DanhSachKyLuat;
    private javax.swing.JTextField tfTienSanCo_DanhSachKyLuat;
    public javax.swing.JTextField tfTongTien_DanhSachKyLuat;
    // End of variables declaration//GEN-END:variables
}
