/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ChucNang_QL_ChamCong;

import DAO.TinhLuongTVDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class SuaCongNhanVienThuViec extends javax.swing.JFrame {

    /**
     * Creates new form SuaCongNhanVienThuViec
     */
    private final Quanly.ChamCong CCform;
    private final TinhLuongTVDAO tinhLuongTVDAO ;
    
    public SuaCongNhanVienThuViec(Quanly.ChamCong ccform) {
        initComponents();
        
        this.CCform = ccform;
        txtMaNVSuaCongNV.setEditable(false);
        tfLuong_SCThuViec.setEditable(false);
        tinhLuongTVDAO = new TinhLuongTVDAO();
    }
    
    private void setWhiteColor()
    {
        bttThem_SCThuViec.setForeground(Color.white);
        bttHuy_SCThuViec.setForeground(Color.white);    
    }
    
    private void reLoadData(){
        List<Model.TinhLuongTV> tinhLuongTVList;
        tinhLuongTVList = tinhLuongTVDAO.getListTinhLuongTV();
        CCform.loadDataToTableTLTV(tinhLuongTVList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new util.PanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfSoGioThem_SCThuViec = new javax.swing.JTextField();
        tfSoNgayCong_SCThuViec = new javax.swing.JTextField();
        tfGhiChu_SCThuViec = new javax.swing.JTextField();
        tfLuong_SCThuViec = new javax.swing.JTextField();
        bttThem_SCThuViec = new util.ButtonGradient();
        bttHuy_SCThuViec = new util.ButtonGradient();
        txtMaNVSuaCongNV = new javax.swing.JTextField();
        txtThang_SCThuViec = new javax.swing.JTextField();
        txtNam_SCThuViec = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Sửa công nhân viên thử việc");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Số ngày công");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Mã nhân viên");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Tháng");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Lương thử việc");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Ghi chú");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Số giờ thêm");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Năm");

        tfSoGioThem_SCThuViec.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfSoGioThem_SCThuViec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfSoNgayCong_SCThuViec.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfSoNgayCong_SCThuViec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfGhiChu_SCThuViec.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfGhiChu_SCThuViec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfLuong_SCThuViec.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfLuong_SCThuViec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bttThem_SCThuViec.setText("Sửa");
        bttThem_SCThuViec.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttThem_SCThuViec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttThem_SCThuViecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttThem_SCThuViecMouseExited(evt);
            }
        });
        bttThem_SCThuViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttThem_SCThuViecActionPerformed(evt);
            }
        });

        bttHuy_SCThuViec.setText("Hủy");
        bttHuy_SCThuViec.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttHuy_SCThuViec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttHuy_SCThuViecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttHuy_SCThuViecMouseExited(evt);
            }
        });
        bttHuy_SCThuViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttHuy_SCThuViecActionPerformed(evt);
            }
        });

        txtThang_SCThuViec.setEditable(false);

        txtNam_SCThuViec.setEditable(false);

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(170, 170, 170))
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelGradient1Layout.createSequentialGroup()
                                .addComponent(tfLuong_SCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel7))
                            .addGroup(panelGradient1Layout.createSequentialGroup()
                                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(panelGradient1Layout.createSequentialGroup()
                                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtThang_SCThuViec, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                            .addComponent(txtMaNVSuaCongNV, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18))
                                    .addGroup(panelGradient1Layout.createSequentialGroup()
                                        .addComponent(txtNam_SCThuViec)
                                        .addGap(17, 17, 17)))
                                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSoNgayCong_SCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSoGioThem_SCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGhiChu_SCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                        .addComponent(bttThem_SCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(bttHuy_SCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(tfSoNgayCong_SCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNVSuaCongNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addComponent(txtThang_SCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGradient1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel9))
                            .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(tfSoGioThem_SCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNam_SCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGhiChu_SCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLuong_SCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttThem_SCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttHuy_SCThuViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttThem_SCThuViecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttThem_SCThuViecMouseEntered
        bttThem_SCThuViec.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttThem_SCThuViecMouseEntered

    private void bttThem_SCThuViecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttThem_SCThuViecMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttThem_SCThuViecMouseExited

    private void bttHuy_SCThuViecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_SCThuViecMouseEntered
        bttHuy_SCThuViec.setForeground(new Color(51, 0, 153));
    }//GEN-LAST:event_bttHuy_SCThuViecMouseEntered

    private void bttHuy_SCThuViecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttHuy_SCThuViecMouseExited
        setWhiteColor();
    }//GEN-LAST:event_bttHuy_SCThuViecMouseExited

    private void bttHuy_SCThuViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttHuy_SCThuViecActionPerformed
        setVisible(false);
    }//GEN-LAST:event_bttHuy_SCThuViecActionPerformed

    private void bttThem_SCThuViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttThem_SCThuViecActionPerformed
        // TODO add your handling code here:
        if(phantichthietkehethong_nhom4.Phantichthietkehethong_nhom4.kiemTraRong(panelGradient1)){
            int soGioThem;
            int soNgayCong;
            String ghiChu = tfGhiChu_SCThuViec.getText();
            String maNVTV = txtMaNVSuaCongNV.getText();
            int thang;
            int nam;
            int luongThuViec;
            int luongThucNhan;
            
            try{
                thang = Integer.parseInt(txtThang_SCThuViec.getText());
                nam = Integer.parseInt(txtNam_SCThuViec.getText());
                luongThuViec = Integer.parseInt(tfLuong_SCThuViec.getText());
                soNgayCong = Integer.parseInt(tfSoNgayCong_SCThuViec.getText());
                soGioThem = Integer.parseInt(tfSoGioThem_SCThuViec.getText());
                luongThucNhan = luongThuViec  + (soGioThem*50000);
                
                tinhLuongTVDAO.UpdateTinhLuongTV(soNgayCong, soGioThem, ghiChu,maNVTV,thang,nam,luongThucNhan);
                JOptionPane.showMessageDialog(rootPane, "Update thành công!");
                reLoadData();
                this.dispose();

            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Error: Nhập sai định dạng!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            }catch(Exception j){
                JOptionPane.showMessageDialog(null, "Error: " + j.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đủ thông tin");
        }
        
    }//GEN-LAST:event_bttThem_SCThuViecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaCongNhanVienThuViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaCongNhanVienThuViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaCongNhanVienThuViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaCongNhanVienThuViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //    new SuaCongNhanVienThuViec().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.ButtonGradient bttHuy_SCThuViec;
    private util.ButtonGradient bttThem_SCThuViec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public util.PanelGradient panelGradient1;
    public javax.swing.JTextField tfGhiChu_SCThuViec;
    public javax.swing.JTextField tfLuong_SCThuViec;
    public javax.swing.JTextField tfSoGioThem_SCThuViec;
    public javax.swing.JTextField tfSoNgayCong_SCThuViec;
    public javax.swing.JTextField txtMaNVSuaCongNV;
    public javax.swing.JTextField txtNam_SCThuViec;
    public javax.swing.JTextField txtThang_SCThuViec;
    // End of variables declaration//GEN-END:variables
}
